<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZF2AuthAcl\Module'                     => __DIR__ . '/Module.php',
    'ZF2AuthAcl\Utility\Acl'                => __DIR__ . '/src/ZF2AuthAcl/Utility/Acl.php',
    'ZF2AuthAcl\Utility\UserPassword'       => __DIR__ . '/src/ZF2AuthAcl/Utility/UserPassword.php',
    'ZF2AuthAcl\Model\ResourceTable'        => __DIR__ . '/src/ZF2AuthAcl/Model/ResourceTable.php',
    'ZF2AuthAcl\Model\PermissionTable'      => __DIR__ . '/src/ZF2AuthAcl/Model/PermissionTable.php',
    'ZF2AuthAcl\Model\User'                 => __DIR__ . '/src/ZF2AuthAcl/Model/User.php',
    'ZF2AuthAcl\Model\UserRole'             => __DIR__ . '/src/ZF2AuthAcl/Model/UserRole.php',
    'ZF2AuthAcl\Model\Role'                 => __DIR__ . '/src/ZF2AuthAcl/Model/Role.php',
    'ZF2AuthAcl\Model\RolePermissionTable'  => __DIR__ . '/src/ZF2AuthAcl/Model/RolePermissionTable.php',
    'ZF2AuthAcl\Form\LoginForm'             => __DIR__ . '/src/ZF2AuthAcl/Form/LoginForm.php',
    'ZF2AuthAcl\Form\Filter\LoginFilter'    => __DIR__ . '/src/ZF2AuthAcl/Form/Filter/LoginFilter.php',
    'ZF2AuthAcl\Controller\IndexController' => __DIR__ . '/src/ZF2AuthAcl/Controller/IndexController.php',
);
