<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Otros\Module'                              => __DIR__ . '/Module.php',
    'Otros\Model\NoticiaTable'                  => __DIR__ . '/src/Otros/Model/NoticiaTable.php',
    'Otros\Controller\NoticiaController'        => __DIR__ . '/src/Otros/Controller/NoticiaController.php',
    'Otros\Controller\IndexController'          => __DIR__ . '/src/Otros/Controller/IndexController.php',
    'Otros\Controller\MailController'          => __DIR__ . '/src/Otros/Controller/MailController.php',
);
