<div style="width: 70%;margin: 0 auto;">
	<div class="content-browser" style="border: 1px solid #ccc;background: #ffffff;margin-top: 45px;padding: 25px;height: 450px">
		<div class="col-lg-12 col-xs-12" style="text-align: center;">
			<h1>Actualiza tu navegador</h1>
			<p>Estás usando una versión de Internet Explorer que no es compatible con <strong>Edificiook</strong>. Para obtener una mejor experiencia, ve a uno de estos sitios y consigue la última versión de tu navegador preferido</p>
		</div>
		<div class="center" style="width: 100%;">
			<div style="width: 33.3%;float: left;">
				<a target="_blank" href="https://www.mozilla.org/es-ES/firefox/new/">
					<img width="215" src="http://infosecawareness.in/gujarati/mozilla-firefox.png/image_preview" alt="">
					<h2>Mozilla Firefox</h2>
				</a>
			</div>
			<div style="width: 33.3%;float: left;">
				<a target="_blank" href="https://support.apple.com/downloads/safari">
					<img width="215" src="http://www.freelogovectors.net/wp-content/uploads/2016/02/safari-icon.png" alt="">
					<h2>Safari</h2>
				</a>
			</div>
			<div style="width: 33.3%;float: left;">
				<a target="_blank" href="https://www.google.com/chrome/browser/desktop/index.html">
					<img width="215" src="https://upload.wikimedia.org/wikipedia/commons/8/87/Google_Chrome_icon_(2011).png" alt="">
					<h2>Google Chrome</h2>
				</a>
			</div>
		</div>
	</div>
</div>		