<div class="row">
    <div class="col-md-offset-1 col-xs-12 col-md-10">
        <div class="page-header">
            <h1> Material informativo 
                <small> <i class="ace-icon fa fa-angle-double-right"></i> Propietarios y Residentes.</small>
            </h1>
        </div>
    </div>
</div>

<div class="col-md-offset-1 col-col-xs-12 col-md-10">
	<div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="0" data-toggle="modal"></a>
            <div class="col-xs-2 col-md-2 nopadding-lef">
                    <div class="wrapper-icon">
                        <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
                    </div>
            </div>
            <div class="col-xs-10 col-md-8">
                <div class="title"><h3>Ingreso al Sistema</h3></div>
                <div class="descripcion"><p>Ingresar el Sistema de gestión de edificios.</p></div>
            </div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green"> Miralo en 1 minuto</span></div>
        </div>
	</div>

	<div class="space-1"></div>
	<div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="1" data-toggle="modal"></a>
    		<div class="col-xs-2 col-md-2 nopadding-lef">
    			<div class="wrapper-icon">
    		        <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
    		    </div>
    		</div>
    		<div class="col-xs-10 col-md-10">
    			<div class="title"><h3>Pizarra electrónica (Dashboard)</h3></div>
    			<div class="descripcion"><p>Muestra información general del edificio (Noticias, Reglamento y manual de operaciones). </p></div>	
    		</div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 3 minutos</span></div>
        </div>
	</div>

	<div class="space-1"></div>
	<div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="2" data-toggle="modal"></a>
    		<div class="col-xs-2 col-md-2 nopadding-lef">
    			<div class="wrapper-icon">
    		        <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
    		    </div>
    		</div>
    		<div class="col-xs-10 col-md-10">
    			<div class="title"><h3>Noticias</h3></div>
    			<div class="descripcion"><p>Noticias del edificio publicadas por el Administrador</p></div>	
    		</div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 2 minutos</span></div>
        </div>
	</div>

	<div class="space-1"></div>
	<div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="3" data-toggle="modal"></a>
    		<div class="col-xs-2 col-md-2 nopadding-lef">
    			<div class="wrapper-icon">
    		        <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
    		    </div>
    		</div>
    		<div class="col-xs-10 col-md-10">
    			<div class="title"><h3>Mis Cuotas</h3></div>
    			<div class="descripcion"><p>Mis cuotas provisionadas, canceladas y pendientes de pago. Aquí también puedo visualizar mi Recibo de mantenimiento y Estado de cuenta emitido.</p></div>	
    		</div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 3 minutos</span></div>
        </div>
	</div>
	<div class="space-1"></div>

     <div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="4" data-toggle="modal"></a>
            <div class="col-xs-2 col-md-2 nopadding-lef">
                <div class="wrapper-icon">
                    <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
                </div>
            </div>
            <div class="col-xs-10 col-md-10">
                <div class="title"><h3>Presupuesto</h3></div>
                <div class="descripcion"><p>Aquí se puede revisar el presupuesto proyectado y ejecutado del Edificio.</p></div> 
            </div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 5 minutos</span></div>
        </div>
    </div>

    <div class="space-1"></div>
    <div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="5" data-toggle="modal"></a>
            <div class="col-xs-2 col-md-2 nopadding-lef">
                <div class="wrapper-icon">
                    <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
                </div>
            </div>
            <div class="col-xs-10 col-md-10">
                <div class="title"><h3>Morosos</h3></div>
                <div class="descripcion"><p>Aquí podemos visualizar los propietarios morosos del Edificio.</p></div>     
            </div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 1 minuto</span></div>
        </div>
    </div>
    <div class="space-1"></div>
    <div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="6" data-toggle="modal"></a>
            <div class="col-xs-2 col-md-2 nopadding-lef">
                <div class="wrapper-icon">
                    <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
                </div>
            </div>
            <div class="col-xs-10 col-md-10">
                <div class="title"><h3>Ingresos</h3></div>
                <div class="descripcion"><p>Aquí podemos revisar los ingresos del Edificio por cada departamento, a nivel de concepto de cuota provisionada, cancelada y pendiente de pago.</p></div>     
            </div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 2 minutos</span></div>
        </div>
    </div>
    <div class="space-1"></div>
    <div class="row-item">
        <div class="wrapper-item">
            <a href="#portfolioModal1" class="item-link" data-item="7" data-toggle="modal"></a>
            <div class="col-xs-2 col-md-2 nopadding-lef">
                <div class="wrapper-icon">
                    <span class="icon-item"><i class="fa fa-play-circle bigger-200"></i></span>
                </div>
            </div>
            <div class="col-xs-10 col-md-10">
                <div class="title"><h3>Balance</h3></div>
                <div class="descripcion"><p>Aquí podemos visualizar el balance general del edificio según mes y año seleccionado. Se puede descargar en formato PDF o visualizarlo directamente en el sistema como Vista Previa.</p></div>     
            </div>
            <div class="duracion_video"><i class="ace-icon fa fa-clock-o purple"></i> <span class="green">Miralo en 1 minuto</span></div>
        </div>
    </div>
    <div class="space-1"></div>
</div>




 <!-- Portfolio Modals -->
    <div class="player-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row-item">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            
                            <section>
                                  <div id="wrapper_video0" class="wrapper_video hidden">
                                        <h2>Ingreso al sistema</h2>
                                        <hr class="star-primary">  
                                        <div data-type="youtube" data-video-id="45_QoSkaxeo"></div>
                                        <p id="text_metavideo">Ingresar el Sistema de gestión de edificios.</p>
                                  </div>
                                  <div id="wrapper_video1" class="wrapper_video hidden">
                                        <h2>Pizarra electrónica</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="7zFmdbmpfWg"></div>
                                        <p id="text_metavideo">Muestra información general del edificio (noticias, reglamento y manual de operaciones). </p>
                                  </div>
                                  <div id="wrapper_video2" class="wrapper_video hidden">
                                        <h2>Noticias</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="YnJ6g7QybYM"></div>
                                        <p id="text_metavideo">Noticias del edificio publicadas por el Administrador</p>
                                  </div>
                                  <div id="wrapper_video3" class="wrapper_video hidden">
                                        <h2>Mis Cuotas</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="wAPibp2Q5ak"></div>
                                        <p id="text_metavideo">Mis cuotas provisionadas, canceladas y pendientes de pago. Aquí también puedo visualizar mi Recibo de mantenimiento y Estado de cuenta emitido.</p>
                                  </div>
                                  <div id="wrapper_video4" class="wrapper_video hidden">
                                        <h2>Presupuesto</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="TPVDehjhCXE"></div>
                                        <p id="text_metavideo">Aquí se puede revisar el presupuesto proyectado y ejecutado del Edificio.</p>
                                  </div>
                                  <div id="wrapper_video5" class="wrapper_video hidden">
                                        <h2>Morosos</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="PI_NeVf6EWQ"></div>
                                        <p id="text_metavideo">Aquí podemos visualizar los propietarios morosos del Edificio.</p>
                                  </div>
                                  <div id="wrapper_video6" class="wrapper_video hidden">
                                        <h2>Ingresos</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="eY2WvUBhgVw"></div>
                                        <p id="text_metavideo">Aquí podemos revisar los ingresos del Edificio por cada departamento, a nivel de concepto de cuota provisionada, cancelada y pendiente de pago.</p>
                                  </div>
                                  <div id="wrapper_video7" class="wrapper_video hidden">
                                        <h2>Balance</h2>
                                        <hr class="star-primary">
                                        <div data-type="youtube" data-video-id="-HON-jgclZM"></div>
                                        <p id="text_metavideo">Aquí podemos visualizar el balance general del edificio según mes y año seleccionado. Se puede descargar en formato PDF o visualizarlo directamente en el sistema como Vista Previa.</p>
                                  </div>
        				    </section>
                            <button type="button" id="closeModal" class="button-close" data-dismiss="modal"><i class="fa fa-times"></i> Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<?php echo $this->inlineScript()
	->appendFile($this->basePath('/reproductor/dist/plyr.js'),'text/javascript')
    /*->appendFile($this->basePath('/reproductor/dist/demo.js'),'text/javascript')
    ->appendFile('https://cdn.rangetouch.com/0.0.9/rangetouch.js','text/javascript')
    ->appendFile('https://cdn.shr.one/0.1.9/shr.js','text/javascript')*/

    ?>
	
    <script>
    
    //plyr.loadSprite("reproductor/dist/demo.svg");
    //var players=plyr.setup();

    var indexVideoView=0;
    players= plyr.setup({
            debug: true,
            title: "Sistema de gestión de edificios.",
            iconUrl: "reproductor/dist/plyr.svg",
            tooltips: {
                controls: !0
            },
            captions: {
                defaultActive: !0
            }
    });

    $(".close-modal, #closeModal").click(function(){
    	players[indexVideoView].stop();
        $(".wrapper_video").addClass('hidden');
    });

    $(".item-link").click(function(){
        indexVideoView=$(this).attr('data-item');
        $("#wrapper_video"+indexVideoView).removeClass('hidden');
    });
    

    </script>