<?php

	$optionsUsuariosPorEdificio='';
	if($this->usuariosPorEdificio){
		foreach ($this->usuariosPorEdificio as $key => $value){
			if($value['tipo']=='PJ'){
				$optionsUsuariosPorEdificio.='<option value="'.$value['id'].'">'.$value['apellido'].'</option>';
			}else{
				$optionsUsuariosPorEdificio.='<option value="'.$value['id'].'">'.$value['nombre']." ".$value['apellido'].'</option>';
			}
		}
	}
?>
<div class="row">
	<div class="col-xs-12">
		<div class="table-header">
			<div class="row">
				<div class="col-xs-4">Presupuesto</div>
				<div class="col-xs-8">
					<div id="btn-actions" class="btn-group pull-right" role="group" aria-label="...">
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="Action.new()">
					  		<i class="glyphicon glyphicon-file"></i>
					  		<span>Nuevo </span>
					  	</button>
					</div>
					<div id="btn-actions" class="btn-group pull-right" role="group" aria-label="...">
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="DateControls.backYear()">
					  		<i class="ace-icon fa fa-angle-left biger-150"></i>
					  	</button>
					  	<button  type="button" class="btn btn-default btn-sm btnOpe">
					  		<span id="currentYear"><?php echo date('Y');?></span>
					  	</button>
					  	<button type="button" class="btn btn-default btn-sm btnOpe" onclick="DateControls.nextYear()">
					  		<i class="ace-icon fa fa-angle-right"></i>
					  	</button>
					</div>
				</div>
			</div>
		</div>
		<table id="grid-table"></table>
		<div id="grid-pager"></div>
	</div>
</div>



<div class="modal fade" id="modalEgresoEjecutado" tabindex="-1" role="dialog" aria-labelledby="labelModalEgresoEjecutado" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title"><span>Detalle de egreso</span></h4>
			</div>
			<div class="modal-body">
				<input type="hidden" id="dte_co_conceptoId" name="" value="">
				<input type="hidden" id="dte_co_proveedorId" name="" value="">
				<input type="hidden" id="dte_co_mes" name="" value="">
				<div style="padding: 0px 0px;">
					<div class="col-md-6">
						<div class="form-group">
							<label for="">Concepto</label>
							<input id="textConceptoNombre" type="text" class="form-control input-sm" value="" readonly>
						</div>	
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="">Proveedor</label>
							<input id="textProveedorRZ" type="text" class="form-control input-sm" value="" readonly>
						</div>
					</div>
				</div>
				
				<div style="padding: 0px 12px;">
					<table id="tblEgresoPorConceptoAndProveedor" class="table table-striped table-hover" style="margin-bottom:0px!important;">
						<thead>
							<tr>
								<th width="30"></th>
								<th width="100"><i class="ace-icon fa fa-caret-right blue"></i> F. Emisión.</th>
								<th width="100"><i class="ace-icon fa fa-caret-right blue"></i> F. Vence.</th>
								<th><i class="ace-icon fa fa-caret-right blue"></i>Documento</th>
								<th width="120"><i class="ace-icon fa fa-caret-right blue"></i> N° Doc</th>
								<th width="120"><div style="text-align: right;"><i class="ace-icon fa fa-caret-right blue"></i> Importe</div></th>
								<th width="30"></th>
								<th width="60"><i class="ace-icon fa fa-caret-right blue"></i>RD</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
						<tfoot></tfoot>
					</table>
				</div>
			</div>
			<div class="modal-footer">
	        	<button type="button" class="btn btn-default btn-sm" data-dismiss="modal"> Cancelar</button>	
	      	</div>
		</div>
	</div>
</div>

	<?php $this->inlineScript()
    ->appendFile($this->basePath('/js/jqGrid/src/i18n/grid.locale-es.js'),'text/javascript')
    ->appendFile($this->basePath('/js/jqGrid/js/jquery.jqGrid.min.js'),'text/javascript')
    ->appendFile($this->basePath('/script/ue/presupuesto.js?t='.time()),'text/javascript')
  
    ?>

