<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Finanzas\Module'                                  => __DIR__ . '/Module.php',
    'Finanzas\Model\PresupuestoTable'                  => __DIR__ . '/src/Finanzas/Model/PresupuestoTable.php',
    'Finanzas\Model\IngresoTable'                      => __DIR__ . '/src/Finanzas/Model/IngresoTable.php',
    'Finanzas\Model\EgresoTable'                       => __DIR__ . '/src/Finanzas/Model/EgresoTable.php',
    'Finanzas\Controller\ControlcontableController' => __DIR__ . '/src/Finanzas/Controller/ControlcontableController.php',
    'Finanzas\Controller\IngresoController'            => __DIR__ . '/src/Finanzas/Controller/IngresoController.php',
    'Finanzas\Controller\EgresoController'             => __DIR__ . '/src/Finanzas/Controller/EgresoController.php',
    'Finanzas\Controller\PresupuestoController'        => __DIR__ . '/src/Finanzas/Controller/PresupuestoController.php',
    'Finanzas\Controller\IndexController'              => __DIR__ . '/src/Finanzas/Controller/IndexController.php',
    'Finanzas\Controller\ConciliacionbancariaController'=> __DIR__ . '/src/Finanzas/Controller/ConciliacionbancariaController.php',
    'Finanzas\Controller\SaldobancoController'=> __DIR__ . '/src/Finanzas/Controller/SaldobancoController.php',
    'Finanzas\Controller\CrepController'=> __DIR__ . '/src/Finanzas/Controller/CrepController.php',
    'Finanzas\Model\ImportaringresoTable'=> __DIR__ . '/src/Finanzas/Model/ImportaringresoTable.php',
    'Finanzas\Model\ConciliacionbancariaTable'=>__DIR__.'/src/Finanzas/Model/ConciliacionbancariaTable.php',
    'Finanzas\Model\SaldobancoTable'=>__DIR__.'/src/Finanzas/Model/SaldobancoTable.php',
);