<div class="row">
	<div class="col-xs-12">
		<div class="table-header">
			<div class="row">
				<div class="col-xs-5">
					<div class="btn-group pull-left" role="group" aria-label="...">
						<button data-toggle="dropdown" class="btn btn-sm btnOpe dropdown-toggle ">
							<i class="ace-icon glyphicon glyphicon-cog bigger-120"></i>
							<i class="ace-icon fa fa-angle-down icon-on-right"></i>
						</button>
						<?php echo $this->partial('menu-egreso.phtml'); ?>
					</div>
					<span>Egreso <small><i class="ace-icon fa fa-angle-double-right"></i> Pagado</small><span>
				</div>
			</div>
		</div>
		<table id="grid-table"></table>
		<div id="grid-pager"></div>
		<div id="jqmsg_emptyrows" class="hidden"><i class="fa fa-exclamation-circle"></i> No hay registros para mostrar.</div>
	</div>
</div>


<div class="modal fade" id="modalEgreso" tabindex="-1" role="dialog" aria-labelledby="labelModalEgreso" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="labelModalEgreso"><span>Egreso</span></h4>
			</div>
			<div class="modal-body">
				<div class="space"></div>
				<form id="formEgreso" action="#" enctype="multipart/form-data">
					<input type="hidden" id="co_egresoId" name="co_egresoId" class="form-control">
					<div class="row">
						<div class="col-xs-12 col-md-6">
							<div class="form-group">
								<label for="selTipoDoc" class="label_1">Tipo de documento</label>
								<select name="selTipoDoc" id="selTipoDoc" class="form-control">
									<option value="0" disabled>Seleccionar</option>
									<option value="FACTURA">FACTURA</option>
									<option value="TICKET FACTURA">TICKET FACTURA</option>
					                <option value="BOLETA">BOLETA</option>
					                <option value="TICKET BOLETA">TICKET BOLETA</option>
					                <option value="RECIBO SERVICIOS PUBLICOS">RECIBO SERVICIOS PUBLICOS</option>
					                <option value="RECIBO POR HONORARIOS">RECIBO POR HONORARIOS</option>
					                <option value="PLANILLA DE HABERES">PLANILLA DE HABERES</option>
					                <option value="COMPROBANTE MOVILIDAD">COMPROBANTE MOVILIDAD</option>
					                <option value="OTROS">OTROS</option>
								</select>
							</div>
						</div>
						<div class="col-xs-4 col-md-2">
							<div class="form-group">
								<label for="textSerie" class="label_1">N° de Serie</label>
								<input type="text" id="textSerie" name="textSerie" value="" placeholder="" class="form-control">
								<span class="e"></span>
							</div>
						</div>
						<div class="col-xs-8 col-md-4">
							<div class="form-group">
								<label for="textNroDocumento" class="label_1">N° de documento</label>
								<input type="text" id="textNroDocumento" name="textNroDocumento" value="" placeholder="" class="form-control">
								<span class="e"></span>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-6">
							<div class="form-group">
								<label for="textSerie" class="label_1">Fecha de emisión</label>
								<input type="text" id="textFechaEmi" name="textFechaEmi" value="" placeholder="00-00-0000" class="form-control datepicker-default fecha">
								<span class="e"></span>
							</div>
						</div>
						<div class="col-xs-6">
							<div class="form-group">
								<label for="textSerie" class="label_1">Fecha de vencimiento</label>
								<input type="text" id="textFechaVence" name="textFechaVence" value="" placeholder="00-00-0000" class="form-control datepicker-default fecha">
								<span class="e"></span>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<div class="form-group">
								<label for="selProveedor" class="label_1">Proveedor</label>
								<select name="selProveedor" id="selProveedor" class="form-control chosen-select">
									<option value="0" disabled>Seleccionar</option>
									<?php 
					            		if($this->proveedor){
					            			foreach ($this->proveedor as $key => $value) {
					            				echo '<option value="'.$value['id'].'">'.$value['razonsocial'].'</option>';
					            			}
					            		}
					            	?>
								</select>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<div class="form-group">
								<label for="selConcepto" class="label_1">Concepto</label>
								<select name="selConcepto" id="selConcepto" class="form-control chosen-select" >
									<option value="0" disabled>Seleccionar</option>
									<?php 
					            		if($this->conceptos){
					            			foreach ($this->conceptos as $key => $value) {
					            				echo '<option value="'.$value['id'].'">'.$value['descripcion'].'</option>';
					            			}
					            		}
					            	?>
								</select>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-6">
							<div class="form-group">
								<label for="textSerie" class="label_1">Importe S/.</label>
								<input type="text" id="textImporte" name="textImporte" value="" placeholder="0.00" class="form-control">
								<span class="e"></span>
							</div>
						</div>
						<div id="wrapper_metroscubicos" class="col-xs-6 hidde">
							<div class="form-group">
								<label for="textSerie" class="label_1">Metros cúbicos (M3)</label>
								<input type="text" id="textM3" name="textM3" value="" placeholder="0" class="form-control" >
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<label for="ta_nota" class="label_1">Nota</label>
							<textarea class="form-control" id="ta_nota" name="ta_nota" placeholder="Escriba una nota." style="resize:none"></textarea>
						</div>
					</div>
					<div class="space"></div>
					<div class="row">
						<div class="col-xs-12">
							<div class="input-group">
							  	<span class="input-group-addon" style="width: 145px;text-align:right">Provisionado Por:</span>
							  	<input id="textRegistradoPor" type="text" class="form-control" value="">
							  	<span class="input-group-addon" style="font-size: 12px;">Fecha: <i id="fechaRegistro">00-00-0000 00:00 __</i></span>
							</div>
							<div class="input-group">
							  	<span class="input-group-addon" style="width: 145px;text-align:right">Procesado Por:</span>
							  	<input id="textProcesadoPor" type="text" class="form-control" value="">
							  	<span class="input-group-addon" style="font-size: 12px;">Fecha: <i id="fechaProceso">00-00-0000 00:00 __</i></span>
							</div>
							<div class="input-group">
							  	<span class="input-group-addon" style="width: 145px;text-align:right">Aprobado Por:</span>
							  	<input id="textAprobadoPor" type="text" class="form-control" value="">
							  	<span class="input-group-addon" style="font-size: 12px;">Fecha: <i id="fechaAprobacion">00-00-0000 00:00 __</i></span>
							</div>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
	        	<button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cerrar</button>
	      	</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalListaPagosEgreso" tabindex="-1" role="dialog" aria-labelledby="labelModalListaPagosEgreso" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="labelModalEgreso"><span>Egreso</span></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
					   <div class="btn-group btn-group-justified" role="group" aria-label="...">
							<div class="btn-group" role="group">
							    <button type="button" class="btn btn-white" id="lbTotalEgreso"><h4>Total</h4> S/. <span>0.00</span></button>
							</div>
							<div class="btn-group" role="group">
							    <button type="button" class="btn btn-white" id="lbTotalPagado"><h4>Pagado</h4> S/. <span>0.00</span></button>
							</div>
							<div class="btn-group" role="group">
							    <button type="button" class="btn btn-white" id="lbTotalDebe"><h4>Debe</h4> S/. <span>0.00</span></button>
							</div>
						</div>
					</div><!-- /.col-lg-6 -->
				</div>
				<div class="space"></div>
				<div class="row">
					<div class="col-md-12">
						<table id="tblEgresosParciales" class="table table-striped table-hover" style="margin-bottom:0px!important;">
						 	<thead>
						 		<tr>
						 			<th></th>
						 			<th width="120"><i class="ace-icon fa fa-caret-right blue"></i> Fecha</th>
						 			<th><i class="ace-icon fa fa-caret-right blue"></i> Banco</th>
						 			<th width="120"><i class="ace-icon fa fa-caret-right blue"></i> Operación</th>
						 			<th width="120"><div style="text-align: right;"><i class="ace-icon fa fa-caret-right blue"></i> Importe</div></th>
						 			<th width="30"></th>
						 		</tr>
						 	</thead>
						 	<tbody>
						 	</tbody>
						 	<tfoot></tfoot>
						</table>
						<div class="msg_listaPagos" style="background-color: #f9f9f9;height: 50px;"><center>No hay pagos registrados en la lista.</center></div>
					</div>
				</div>
				<div class="space"></div>
			</div>
			<div class="modal-footer">
	        	<button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cerrar</button>
	      	</div>
		</div>
	</div>
</div>


<div class="modal fade" id="modalConfirmacionEliminarEP" tabindex="-1" role="dialog" aria-labelledby="labelModalConfirmacion" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title"><span>Egreso</span></h4>
			</div>
			<div class="modal-body">
				<input type="hidden" id="co_idPagoDelete" value="">
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group" style="height: 50px;">
							<span class="ace-icon question-button bigger-200">?</span>
							<div style="padding-left: 50px; font-size: 15px;">¿Está seguro de eliminar el pago seleccionado?</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<center>
					<button id="btnConfirmarEliminarEP" type="button" class="btn btn-danger btn-sm" onclick="Action.deleteEP()"> Aceptar</button>
	        		<button type="button" class="btn btn-default btn-sm" data-dismiss="modal"> Cancelar</button>	
				</center>
	      	</div>
		</div>
	</div>
</div>



<?php $this->inlineScript()
    ->appendFile($this->basePath('/js/jqGrid/src/i18n/grid.locale-es.js'),'text/javascript')
    ->appendFile($this->basePath('/js/jqGrid/js/jquery.jqGrid.min.js'),'text/javascript')
    ->appendFile($this->basePath('/js/slidereveal/js/slidereveal.js'),'text/javascript')
    ->appendFile($this->basePath('/script/finanzas/egreso_pagado.js?t='.time()),'text/javascript')  
?>