<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Seguridad\Module'                                  => __DIR__ . '/Module.php',
    'Seguridad\Model\AuditoriaTable'              => __DIR__ . '/src/Seguridad/Model/AuditoriaTable.php',
    'Seguridad\Model\UseraccessTable'              => __DIR__ . '/src/Seguridad/Model/UseraccessTable.php',
    'Seguridad\Controller\IndexController'              => __DIR__ . '/src/Seguridad/Controller/IndexController.php',
    'Seguridad\Controller\UseraccessController'              => __DIR__ . '/src/Seguridad/Controller/UseraccessController.php',
    'Seguridad\Controller\AuditoriaController'              => __DIR__ . '/src/Seguridad/Controller/AuditoriaController.php',
);