<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Mantenimiento\Module'                            => __DIR__ . '/Module.php',
    'Mantenimiento\Model\EdificioTable'               => __DIR__ . '/src/Mantenimiento/Model/EdificioTable.php',
    'Mantenimiento\Model\Entity\Edificio'             => __DIR__ . '/src/Mantenimiento/Model/Entity/Edificio.php',
    'Mantenimiento\Model\Entity\Tipo'                 => __DIR__ . '/src/Mantenimiento/Model/Entity/Tipo.php',
    'Mantenimiento\Model\Entity\Departamento'         => __DIR__ . '/src/Mantenimiento/Model/Entity/Departamento.php',
    'Mantenimiento\Model\DepartamentoTable'           => __DIR__ . '/src/Mantenimiento/Model/DepartamentoTable.php',
    'Mantenimiento\Model\ConceptoTable'           => __DIR__ . '/src/Mantenimiento/Model/ConceptoTable.php',
    'Mantenimiento\Model\UsuarioTable'           => __DIR__ . '/src/Mantenimiento/Model/UsuarioTable.php',
    'Mantenimiento\Model\ProveedorTable'           => __DIR__ . '/src/Mantenimiento/Model/ProveedorTable.php',
    'Mantenimiento\Controller\EdificioController'     => __DIR__ . '/src/Mantenimiento/Controller/EdificioController.php',
    'Mantenimiento\Controller\ConceptoController'     => __DIR__ . '/src/Mantenimiento/Controller/ConceptoController.php',
    'Mantenimiento\Controller\UsuarioController'      => __DIR__ . '/src/Mantenimiento/Controller/UsuarioController.php',
    'Mantenimiento\Controller\DepartamentoController' => __DIR__ . '/src/Mantenimiento/Controller/DepartamentoController.php',
    'Mantenimiento\Controller\ProveedorController'    => __DIR__ . '/src/Mantenimiento/Controller/ProveedorController.php',
    'Mantenimiento\Controller\IndexController'        => __DIR__ . '/src/Mantenimiento/Controller/IndexController.php',
    'Mantenimiento\Controller\ConfiguraciondereservasController'        => __DIR__ . '/src/Mantenimiento/Controller/ConfiguraciondereservasController.php',
);
