<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reporte\Module'                            => __DIR__ . '/Module.php',
    'Proceso\Model\Entity\Cuota'                => __DIR__ . '/src/Reporte/Model/Entity/Cuota.php',
    'Reporte\Model\EstadoCuentaTable'           => __DIR__ . '/src/Reporte/Model/EstadoCuentaTable.php',
    'Reporte\Model\BalanceTable'                => __DIR__ . '/src/Reporte/Model/BalanceTable.php',
    'Reporte\Controller\EstadoCuentaController' => __DIR__ . '/src/Reporte/Controller/EstadoCuentaController.php',
    'Reporte\Controller\BalanceController'      => __DIR__ . '/src/Reporte/Controller/BalanceController.php',
    'Reporte\Controller\IndexController'        => __DIR__ . '/src/Reporte/Controller/IndexController.php',
);
