<div class="error-container">
    <div class="well">
        <h1 class="grey lighter smaller">
            <span class="blue bigger-125">
                <i class="fa fa-info-circle"></i>
                Lo sentimos.
            </span>
            Esta opción se encuentra en mantenimeinto
        </h1>
        <hr />
        <h3 class="lighter smaller">
            <i class="ace-icon fa fa-wrench icon-animated-wrench bigger-125"></i>
            Nuestro equipo esta haciendo el mayor esfuerzo para finalizar lo antes posible.
        </h3>
        <div class="space"></div>
        <div>
            <h4 class="lighter smaller">Le agradecemos de antemano su paciencia.</h4>
        </div>
        <hr />
        <div class="space"></div>
        <div class="center">
            <a href="javascript:history.back()" class="btn btn-grey">
                <i class="ace-icon fa fa-arrow-left"></i>
                Regresar
            </a>
            <a href="#" class="btn btn-success">
                <i class="ace-icon fa fa-tachometer"></i>
                Dashboard
            </a>
        </div>
    </div>
</div>
