<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-md-12">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar edificio">
                    <span class="input-group-addon" id="sizing-addon3">@</span>
                </div>
            </div>
        </div>
        <div class="space"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="list-group">
                    <a href="#" class="list-group-item active">
                        <span class="menu-icon fa  fa-home" ></span> Edificio del Mar
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="menu-icon fa  fa-home"></span> Edificio City
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="menu-icon fa  fa-home"></span> El polo 401
                    </a>
                    <a href="#" class="list-group-item">
                        <span class="menu-icon fa  fa-home"></span> Edificio Tenderini
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
