<!DOCTYPE html>
<html>
<head>
	<title>Resumen Financiero al <?= $this->data_balance['fechaBalance']; ?></title>
	<meta charset="utf-8">
	<?php
		$colores=array();
		$colores['colores']=array("h3"=>"#f5f5f5");

		$timeBalance=strtotime(str_replace("/", "-", $this->data_balance['fechaBalance']));
		$diaBalance=date('d',$timeBalance);
		$mesBalance=(int)date('m',$timeBalance);
		$yearBalance=(int)date('Y',$timeBalance);

		$fechaBalanceText="AL ".$diaBalance." DE ".strtoupper($this->meses[$mesBalance])." DEL ".$yearBalance;

	?>
	<style>
		@import url('https://fonts.googleapis.com/css?family=Open+Sans:300');
		.container{
			margin-left: auto;
			margin-right: auto;
			width: 100%;
			background-color: #ffffff;
		}
		table {
			width: 100%;
		}
		section{
			margin-bottom: 10px;
		}

		h1, h2, h3, h4, h5{
			margin: 0px;
		}

		.money{
			text-align: right;	
		}

		tr.break-bgTotal{
			background: #e7ecf1;
		    font-size: 13px;
		    height: 30px;
		}
		tr.break-bgTotal th:first-child{
			text-align: right;
		}

		tr.break-bgTotal th{
			border-top: 1px solid #2273b6;
		}

		tr.rowLevel1 td{
			font-size: 13px;
			font-weight: 600;
		}
		tr.rowLevel2 td{
			font-size: 10px;
			font-weight: 600;
		}
		tr.rowLevel2 td:first-child{
			padding-left: 10px;
		}
		tr.rowLevel3 td:first-child{
			padding-left: 30px;
		}



		/*Section 1:*/
		.section1 .wrapper-titles{
			text-align: center;
		}
		.section1 h2.title{
			visibility: visible;
		    font-family: "Open Sans script=latin rev=3";
		    font-style: normal;
		}


		/*Section 2*/
		.section2 table tr th.header{
			font-size: 12px;
			font-weight: 400;
			border: 1px solid #555555;
			text-align: center;
		}
		.section2 table tr td.value{
			font-size: 11px;
			font-weight: 400;
			border:1px solid #555555; text-align: right;
		}



		/* Section ingresos:*/
		#ingresos table{
			font-size: 10px;
		}
		#ingresos table tr.rowLevel3 td{
			font-size: 9px;
			padding-top: 0px;
			padding-bottom: 0px;
		}

		/*Section egresos*/
		#egresos table{
			font-size: 10px;
		}
		#egresos table tr.rowLevel2 td{
			padding-top: 0px;
			padding-bottom: 0px;
		}
		#egresos table tr.rowLevel3 td{
			font-size: 9px;
			padding-top: 0px;
			padding-bottom: 0px;
		}


		/*Section ingresos pendientes*/
		#ingresos_pendientes table{
			font-size: 10px;
		}
		#ingresos_pendientes tr.rowLevel3 td{
			font-size: 10px;
			padding-top: 0px;
			padding-bottom: 0px;
		}


		/*Section egresos pendientes*/
		#egresos_pendientes table{
			font-size: 10px;
		}
		#egresos_pendientes tr.rowLevel3 td{
			font-size: 9px;
			padding-top: 0px;
			padding-bottom: 0px;
		}


		/*Section Saldo Contable*/
		#saldoContable table tr th.header{
			font-size: 12px;
			font-weight: 400;
			border: 1px solid #555555;
			text-align: center;
		}
		#saldoContable table tr td.value{
			font-size: 11px;
			font-weight: 400;
			border:1px solid #555555; text-align: right;
		}

		#FirmaAdministrador{
			padding-top: 50px;
		}






		/* Page Breaks */

/***Always insert a page break before the element***/
       .pb_before {
           page-break-before: always !important;
       }

/***Always insert a page break after the element***/
       .pb_after {
           page-break-after: always !important;
       }

/***Avoid page break before the element (if possible)***/
       .pb_before_avoid {
           page-break-before: avoid !important;
       }

/***Avoid page break after the element (if possible)***/
       .pb_after_avoid {
           page-break-after: avoid !important;
       }

/* Avoid page break inside the element (if possible) */
       .pbi_avoid {
           page-break-inside: avoid !important;
       }



	</style>
</head>
<body>

	<div class="container">
		<section class="section1">
			<div class="wrapper-titles">
				<h2>RESUMEN FINANCIERO</h2>
				<h5><?= $fechaBalanceText?></h5>
				<h3><?= $this->data_balance['edificio']['nombre'] ?></h3>
			</div>
		</section>
		<section class="section2">
			<table border="0" cellpadding="2" cellspacing="0">
				<tr>
					<th class="header" style="width: 22%;">SALDO BANCO AL<br>
						<span style="font-size: 10px;" id="fechaSaldoBancoMesAnterior"></span>
					</th>
					<th style="width: 5%;">&nbsp;</th>
					<th class="header" style="width: 21%;">TOTAL INGRESOS <br> <span id="fechaIngresos"></span></th>
					<th class="header" style="width: 21%;">TOTAL EGRESOS <br> <span id="fechaEgresos"></span></th>
					<th style="width: 10%">&nbsp;</th>
					<th class="header" style="width: 21%;">SALDO EN BANCO<br>
						<span id="fechaSaldoBanco"></span>
					</th>
				</tr>
				<tr>
					<td class="value" style="">S/ <span id="SaldoAnterior"></span></td>
					<td style="">&nbsp;</td>
					<td class="value">S/ <span id="TotalIngreso">0.00</span></td>
					<td class="value">S/ <span id="TotalEgreso">0.00</span></td>
					<td style="">&nbsp;</td>
					<td class="value">S/ <span id="SaldoBanco">0.00</span></td>
				</tr>
			</table>
		</section>



		<section id="ingresos">
			<div class="row">
				<hr>
				<h3 style="margin: 0px;"><?= ($this->tipo_balance=='detallado')? 'DETALLE DE ':''; ?>INGRESOS</h3>
				<table border="0" cellpadding="2" cellspacing="0" style="width: 100%">
					<?php
						$sumTotalIngresos=0;
						$htmlRowsIngresos="";

						foreach ($this->data_balance['INGRESOS_AL'] as $key=>$ipa) {
							$htmlRowsIngresos.='
							<tr class="rowLevel3"><td style="width: 20%;">'.$ipa['unidad'].'</td>
								<td>'.$this->meses[$ipa['mesEmi']]." ".$ipa['yearEmi'].' ('.$ipa['nro_serie']."-". $ipa['nro_doc'].')</td>
								<td class="money">'.$ipa['totalEmitido'].'</td>
								<td></td>
								<td class="money">'.number_format($ipa['importe'],2,".",",").'</td>
							<tr>';
							$sumTotalIngresos+=$ipa['importe'];
						}
					?>

					<?php 
						if($this->tipo_balance=='detallado'){
					?>
						<tr class="rowLevel1">
							<th style="width: 20%;">Unidad</th>
							<th style="width: 20%;">Emisión</th>
							<th style="width: 10%; text-align: left;">Total Emisión</th>
							<th style="width: 30%;">&nbsp;</th>
							<th style="width: 20%; text-align: right;">Pago Registrado</th>
						</tr>
					<?php
							echo $htmlRowsIngresos;
						}
					?>
					<tr class="break-bgTotal">
						<th colspan="4">Total ingresos al <?= $this->data_balance['fechaBalance']; ?></th>
						<th class="money" >S/ <?= number_format($sumTotalIngresos,2,".",",");?></th>
					</tr>
				
				</table>
			</div>
		</section>



		<section id="egresos">
			<h3 style="margin: 0px;"><?= ($this->tipo_balance=='detallado')? 'DETALLE DE ':''; ?>EGRESOS</h3>
			<table border="0" cellpadding="2" cellspacing="0" style="width: 100%">
				<?php

					$dataEgresosAl=$this->data_balance['EGRESOS_AL'];
					$sumTotalEgresos=0;

					foreach ($dataEgresosAl as $egresos) {
						if (count($egresos['rows'])<=0 ){
							continue;
						}
						echo '<tr class="rowLevel1"><td colspan="4">'.$egresos['grupo'].'</td></td>';

						foreach ($egresos['rows'] as $conceptos) {

							if(count($conceptos['rows']) < 0) {
								continue;
							}

							$proveedorPorConcepto=$conceptos['rows'];
							$htmlRowsProveedor="";
							$totalRowsConceptosProveedor=0;

							foreach ($proveedorPorConcepto as $egresoProveedor) {
								$htmlRowsProveedor.= '<tr class="rowLevel3">
									<td>'.$egresoProveedor['observacion'].'</td>
									<td>'.$egresoProveedor['numero_recibo'].'</td>
									<td>'.$egresoProveedor['razonsocial'].'</td>
									<td class="money">'.number_format($egresoProveedor['total'],2,".",",").'</td>
									</tr>';
								$totalRowsConceptosProveedor+=$egresoProveedor['total'];

							}
							echo '<tr class="rowLevel2">
							<td colspan="3">'.$conceptos['concepto'].'</td>
							<td class="money">'.number_format($conceptos['total'],2,".",",") .'</td>
							</tr>';

							echo $htmlRowsProveedor;
							$sumTotalEgresos+=$totalRowsConceptosProveedor;
						}

					}
				?>
				<tr class="break-bgTotal">
					<th colspan="3">Total egresos al <?= $this->data_balance['fechaBalance']; ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
					<th class="money">S/ <?= number_format($sumTotalEgresos,2,".",","); ?></th>
				</tr>	
			</table>
		</section>





		<section id="ingresos_pendientes">
			<hr>
			<h3 style="margin: 0px;">PENDIENTES POR COBRAR</h3>
			<table border="0" cellpadding="2" cellspacing="0" style="width: 100%">
				<?php
					/*
					CONSIDERAR LO SIGUIENTE EN ESTA SECCION: 
					*Informe Resumido: Las cuotas pendientes del mes aparecera totalizado, las superiores a un mes de antiguedad aparecera agrupado por unidad.
					*Informe Detallado: Las cuotas se visualizaran agrupadas por unidad (En la agrupacion de c/u se mostrara ordenado en forma descendente por fecha de emisison).
					*/

					$ingresosPendientesPorCobrar=$this->data_balance['INGRESOS_PENDIENTEPAGO_AL'];
					$labelPeriodoBalance=$this->meses[$mesBalance]." ".$yearBalance;

					$htmlRows="";
					$totalPendientePorCobrarMes=0;
					$totalPendientePorcobrar=0;
					$sumTotalIngresosPendientes=0;

					$lastRow=null;
					for ($i=0; $i < count($ingresosPendientesPorCobrar); $i++) {

						$currentRow=$ingresosPendientesPorCobrar[$i];

						$labelPeriodo=$this->meses[$currentRow['mesEmi']]." ".$currentRow['yearEmi'];
						

						if($this->tipo_balance=='resumido'){
							if($labelPeriodo==$labelPeriodoBalance){
								$totalPendientePorCobrarMes+=$currentRow['debe'];
								continue;
							}
						}
						
						if($currentRow['idUnidad']==$lastRow['idUnidad']){
							$htmlRows.='<tr class="rowLevel3">
								<td></td>
								<td>'. $labelPeriodo.' ('.$currentRow['nro_serie']."-". $currentRow['nro_doc'].')</td>
								<td class="money">'.number_format($currentRow['debe'],2,".",",").'</td>
							</tr>';
						}else{
							$htmlRows.='<tr class="rowLevel3">
								<td>'.$currentRow['unidad'].'</td>
								<td>'.$labelPeriodo.' ('.$currentRow['nro_serie']."-". $currentRow['nro_doc'].')</td>
								<td class="money">'.number_format($currentRow['debe'],2,".",",").'</td>
							</tr>';
						}

						$totalPendientePorcobrar+=$currentRow['debe'];
						$lastRow=$currentRow;
					}

					$sumTotalIngresosPendientes=$totalPendientePorCobrarMes + $totalPendientePorcobrar;

				?>

					<tr class="rowLevel1">
						<td colspan="3"><?= ($this->tipo_balance=='resumido' && $totalPendientePorcobrar>0) ? 'Detalle de pendientes por cobrar superiores a un mes de antiguedad': ''; ?></td>
					</tr>

					<?php if($this->tipo_balance=='detallado' && $totalPendientePorcobrar>0)  {?>
						<tr class="rowLevel2">
							<td style="width: 25%;">Unidad</td>
							<td style="width: 50%;">Emisión</td>
							<td style="width: 25%;" class="money">Debe (S/)</td>
						</tr>
					<?php
					}
					echo $htmlRows;
					?>
					

					<?php if($this->tipo_balance=='resumido') { ?>
					<tr class="rowLevel1">
						<td colspan="2">Pendientes por cobrar de <?=$labelPeriodoBalance; ?> </td>
						<td class="money"><?= number_format($totalPendientePorCobrarMes,2,".",","); ?></td>
					</tr>
					<?php } ?>


					<tr class="break-bgTotal">
						<th colspan="2">Total pendientes por cobrar al <?= $this->data_balance['fechaBalance']; ?></th>
						<th class="money">S/ <?= number_format($sumTotalIngresosPendientes,2,".",","); ?></th>
					</tr>
			</table>
		</section>






		<section id="egresos_pendientes">
			<h3 style="margin: 0px;">PENDIENTES POR PAGAR</h3>
			<table border="0" cellpadding="2" cellspacing="0" style="width: 100%">
				<?php

				$egresoPendienteAl=$this->data_balance['EGRESOS_PENDIENTEPAGO_AL'];
				$sumTotalEgresosPendientes=0;
					foreach ($egresoPendienteAl as $egresos) {
						if (count($egresos['rows'])<=0 ){
							continue;
						}
						echo '<tr class="rowLevel1"><td colspan="4">'.$egresos['grupo'].'</td></td>';

						foreach ($egresos['rows'] as $conceptos) {

							if(count($conceptos['rows']) < 0) {
								continue;
							}

							$proveedorPorConcepto=$conceptos['rows'];

							$htmlRowsProveedor="";
							$totalRowsConceptosProveedor=0;
							foreach ($proveedorPorConcepto as $egresoProveedor) {
								$debe=$egresoProveedor['debe'];

								$htmlRowsProveedor.='<tr class="rowLevel3">
									<td>'.$egresoProveedor['observacion'].'</td>
									<td>'.$egresoProveedor['numero_recibo'].'</td>
									<td>'.$egresoProveedor['razonsocial'].'</td>
									<td class="money">'.number_format($debe,2,".",",").'</td>
									</tr>';
								$totalRowsConceptosProveedor+=$debe;
							}

							echo '<tr class="rowLevel2">
							<td colspan="3">'.$conceptos['concepto'].'</td>
							<td class="money">'.number_format($totalRowsConceptosProveedor,2,".",",").'</td>
							</tr>';
							echo $htmlRowsProveedor;
							$sumTotalEgresosPendientes+=$totalRowsConceptosProveedor;
						}

					}
				?>
				<tr class="break-bgTotal">
					<th colspan="3">Total pendientes por pagar al <?= $this->data_balance['fechaBalance']; ?> </th>
					<th class="money">S/ <?= number_format($sumTotalEgresosPendientes,2,".",","); ?></th>
				</tr>
			</table>
		</section>


		<section id="saldoContable" class="pb_before_____">
			<h3 style="margin:0px;">INFORMACIÓN DEL MES</h3>
			<table border="0" cellpadding="2" cellspacing="0">
				<tr>
					<th class="header" style="width: 22%;">SALDO EN BANCO<br>
						<span style="font-size: 10px;" id="sc_fechaSaldoBanco"></span>
					</th>
					<th style="width: 5%;">&nbsp;</th>
					<th class="header" style="width: 21%;">PENDIENTES POR COBRAR</th>
					<th class="header" style="width: 21%;">PENDIENTES POR PAGAR</th>
					<th style="width: 10%">&nbsp;</th>
					<th class="header" style="width: 21%;">SALDO CONTABLE<br>
						<span style="font-size: 10px;" id="sc_fechaSaldoContable"></span>
					</th>
				</tr>
				<tr>
					<td class="value">S/ <span id="sc_saldoBanco"></span></td>
					<td style="">&nbsp;</td>
					<td class="value">S/<span id="TotalIngresoPendiente">0.00</span></td>
					<td class="value">S/<span id="TotalEgresoPendiente">0.00</span></td>
					<td style="">&nbsp;</td>
					<td class="value">S/<span id="SaldoContable">0.00</span></td>
				</tr>
			</table>
		</section>

		<section id="FirmaAdministrador">
			<table cellspacing="0" style="width: 100%;text-align:center;">
				<tr>
					<td style="width:70%;">&nbsp;</td>
					<td style="width:30%; border-top: 1px solid #000; text-align: center;">
						<p style="font-size:12px; margin:0px; padding-top: 5px;"><?= $this->data_balance['edificio']['administrador']; ?></p>
						<p style="margin:0px;">(Administrador)</p>
					</td>
				</tr>
			</table>
		</section>
		
		<?php

			$dataSaldoBancoMesAnterior=$this->data_balance['saldoBancoMesAnterior'];

			// informacion para el resumen:+
			$saldoAnterior=$dataSaldoBancoMesAnterior['total'];
			$saldoEnBanco=($saldoAnterior + $sumTotalIngresos) - $sumTotalEgresos;
			$saldoContable=($saldoEnBanco + $sumTotalIngresosPendientes) - $sumTotalEgresosPendientes;

		?>
		<script>
			document.getElementById('fechaSaldoBancoMesAnterior').innerHTML='<?= $dataSaldoBancoMesAnterior["fecha"]; ?>';
			//SALDO EN BANCO - TOP
			document.getElementById('SaldoAnterior').innerHTML='<?= number_format($saldoAnterior,2,".",","); ?>';
			document.getElementById('TotalIngreso').innerHTML='<?= number_format($sumTotalIngresos,2,".",","); ?>';
			document.getElementById('TotalEgreso').innerHTML='<?= number_format($sumTotalEgresos,2,".",","); ?>';

			document.getElementById('fechaSaldoBanco').innerHTML='<?= $this->data_balance['fechaBalance']; ?>';
			document.getElementById('SaldoBanco').innerHTML='<?= number_format($saldoEnBanco,2,".",","); ?>';
			
			//SALDO CONTABLE - FOOTER
			document.getElementById('sc_saldoBanco').innerHTML='<?= number_format($saldoEnBanco,2,".",","); ?>';
			document.getElementById('sc_fechaSaldoBanco').innerHTML='<?= $this->data_balance['fechaBalance']; ?>';

			document.getElementById('TotalIngresoPendiente').innerHTML='<?= number_format($sumTotalIngresosPendientes,2,".",","); ?>';
			document.getElementById('TotalEgresoPendiente').innerHTML='<?= number_format($sumTotalEgresosPendientes,2,".",","); ?>';
			
			document.getElementById('sc_fechaSaldoContable').innerHTML='<?= $this->data_balance['fechaBalance']; ?>';
			document.getElementById('SaldoContable').innerHTML='<?= number_format($saldoContable,2,".",","); ?>';

			
		</script>
	</div>
</body>
</html>