<style>
  .btn-estandar{
    position: fixed;
    padding: 10px;
    text-align: center;
    bottom: 25px;
    right: 25px; 
  }
  .btn-estandar .flex{
    font-weight: 700;
    width: 50px;
    height: 50px;
    border-radius: 100%;
    background: rgba(214, 22, 8, 0.81);
    border: 1px solid transparent;
  }
  .btn-estandar .flex:hover{
    background: rgba(214, 22, 8, 0.81);
    border: 1px solid transparent;
  }
  .btn-estandar .flex:focus{
    background: rgba(214, 22, 8, 0.81);
    border: 1px solid transparent;
  }
  .flex i{
    font-size: 27px;
    color: #fff;
    margin-top: 4px;
  }
</style>


<?

if($this->typeRender=='html'){
  echo '<div class="btn-estandar">
        <div class="flex btn btn-default format-white" onclick="recibo.cambiarFormatoRecibo(this)" formato="0" style="border: 1px solid #333;background-color:#FFF;" data-toggle="tooltip" data-placement="top" title="Ver formato Pre Impreso"></div>
        <div class="flex btn btn-default generate" onclick="recibo.crearPdf()" data-toggle="tooltip" data-placement="top" title="Generar PDF">
          <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
        </div>
      </div>';
}

?>



<?php echo $this->headLink()
    ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
    ->appendStylesheet($this->basePath('css/font-awesome.min.css')) 
?>

<!-- UBIGEO -->


<div class="modal fade" id="myModalReciboProgress" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    <div class="modal-body">
      <div class="row">
        <div class="col-lg-12" style="text-align: center;">
          <i class="fa fa-circle-o-notch fa-spin" style="font-size: 100px;margin-bottom: 15px;color: #C15F9D;"></i>
          <p style="font-weight: 800;color: #555;">Generando PDF...</p>
        </div>
      </div>
    </div>
     
    </div>
  </div>
</div>


<?php echo $this->inlineScript()
	->appendFile($this->basePath('/js/jquery.min.js'),'text/javascript')
  ->appendFile($this->basePath('/js/bootstrap.min.js'),'text/javascript')
  ->appendFile($this->basePath('/script/reporte/ec-reporte.js'),'text/javascript')
?>

<script>
  recibo.month = '<?php echo $this->month; ?>';
  recibo.year = '<?php echo $this->year; ?>';
  recibo.type = '<?php echo $this->type; ?>';
  recibo.idrow = '<?php echo $this->idrow; ?>';
  recibo.filterx = '<?php echo $this->filterx; ?>';
  recibo.admin = '<?php echo $this->admin; ?>';
</script>
