<style>
  @media (max-width: 800px){
      .content-detallado{
        width: 100%!important;
      }
  }
  .btn-estandar{
    background: #ddd;
    padding-top: 20px;
    padding: 18px;
    text-align: center;
    margin-top: 20px;
  }
</style>

<div class="btn-estandar">
	<button type="botton" class="btn btn-default" onclick="recibo.crearPdf()">DESCARGAR PDF</button>
  <img src="images/ok.svg" width="25" class="hide">
</div>

<?php echo $this->headLink()
    ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
    ->appendStylesheet($this->basePath('css/font-awesome.min.css')) 
?>

<!-- UBIGEO -->
<div class="modal fade" id="myModalReciboProgress" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    <div class="modal-body">
      <div class="row">
        <div class="col-lg-12" style="text-align: center;">
          <i class="fa fa-circle-o-notch fa-spin" style="font-size: 100px;margin-bottom: 15px;color: #C15F9D;"></i>
          <p style="font-weight: 800;color: #555;">Generando PDF...</p>
        </div>
      </div>
    </div>
     
    </div>
  </div>
</div>

<?php echo $this->inlineScript()
	->appendFile($this->basePath('/js/jquery.min.js'),'text/javascript')
  ->appendFile($this->basePath('/js/bootstrap.min.js'),'text/javascript')
  ->appendFile($this->basePath('/script/reporte/ec-reporte2.js'),'text/javascript')
?>

<script>
  recibo.month = '<?php echo $this->month; ?>';
  recibo.year = '<?php echo $this->year; ?>';
  recibo.type = '<?php echo $this->type; ?>';
  recibo.idrow = '<?php echo $this->idrow; ?>';
  recibo.filterx = '<?php echo $this->filterx; ?>';
  recibo.admin = '<?php echo $this->admin; ?>';
</script>