<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Proceso\Module'                            => __DIR__ . '/Module.php',
    'Proceso\Model\Entity\Cuota'                => __DIR__ . '/src/Proceso/Model/Entity/Cuota.php',
    'Proceso\Model\CuotaTable'                  => __DIR__ . '/src/Proceso/Model/CuotaTable.php',
    'Proceso\Model\ConsumoTable'                => __DIR__ . '/src/Proceso/Model/ConsumoTable.php',
    'Proceso\Form\CuotaForm'                    => __DIR__ . '/src/Proceso/Form/CuotaForm.php',
    'Proceso\Controller\CuotaController'        => __DIR__ . '/src/Proceso/Controller/CuotaController.php',
    'Proceso\Controller\ConsumoController'      => __DIR__ . '/src/Proceso/Controller/ConsumoController.php',
    'Proceso\Controller\IndexController'        => __DIR__ . '/src/Proceso/Controller/IndexController.php',
);
