<?php echo $this->doctype();
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public'); 
}

?>
<html lang="es">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta charset="utf-8">
    <base href="<?php echo $this->serverUrl().$this->basePath()."/";?>" />

    <?php echo $this->headTitle($this->Theme()['titulo_login'])->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->appendName( 'autor' ,  'SOTWARE FACTORY - KND S.A.C')
    ->appendName( 'keywords' ,  '')
    ?>
    <!-- bootstrap & fontawesome -->
     <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'images/favicon.png', 'href' => $this->basePath() . '/images/favicon.png'))
    ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
    ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
    ->appendStylesheet($this->basePath('css/ace-fonts.css'))
    ->appendStylesheet($this->basePath('css/ace.min.css'))
    /*->appendStylesheet($this->basePath('css/ace-skins.min.css'))*/
    ->appendStylesheet($this->basePath('css/ace-rtl.min.css'))
    ->appendStylesheet($this->basePath('css/ace.onpage-help.css'))
    ->appendStylesheet($this->basePath('css/jquery.gritter.css'))
    ->appendStylesheet($this->basePath('css/browser.css'))
    ->appendStylesheet($this->basePath($this->Theme()['ruta_theme']))
    /*->appendStylesheet($this->basePath('js/themes/sunburst.css'))*/
    ?>
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
		<script src="js/respond.min.js"></script>
		<![endif]-->
</head>

<body class="b-login">

    <?php 

	    $userAgent=$_SERVER['HTTP_USER_AGENT'];
	    $responseBrowser='';
	    if(strpos($userAgent, 'MSIE') !== FALSE){
	        $responseBrowser = 'IE';
	    }elseif(strpos($userAgent, 'Edge') !== FALSE) {//Microsoft Edge
	        $responseBrowser = 'Microsoft Edge';
	    }elseif(strpos($userAgent, 'Trident') !== FALSE) {//IE 11
	        $responseBrowser = 'IE';
	    }elseif(strpos($userAgent, 'Opera Mini') !== FALSE){
	        $responseBrowser = "OPERA";
	    }elseif(strpos($userAgent, 'Opera') || strpos($userAgent, 'OPR') !== FALSE){
	        $responseBrowser = "OPERA";
	    }elseif(strpos($userAgent, 'Firefox') !== FALSE) {
	        $responseBrowser = 'MOZILLA';
	    }elseif(strpos($userAgent, 'Chrome') !== FALSE){
	        $responseBrowser = 'CHROME';
	    }elseif(strpos($userAgent, 'Safari') !== FALSE){
	        $responseBrowser = "SAFARI";
	    }else{
	        $responseBrowser = 'No hemos podido detectar su navegador';
	    }
	    if($responseBrowser ==='IE'){
	        echo '
	            <div class="gritter-item-wrapper gritter-left gritter-browser" style="">
	            	<div class="gritter-top"></div>
	            	<div class="gritter-item">
	            		<div class="gritter-close" style="display: none;">
	            	</div>
	            	<div class="gritter-without-image">
	            		<span class="gritter-title">
	            			<img src="http://localhost:8080/edificiookplus/public/images/iconos/warning.png" class="gritter-image"> Para mejorar tu experiencia en edificiook, <a href="../browser">actualiza tu navegador</a>.
	            		</span>
	            		<p></p>
	            	</div>
	            	<div style="clear:both"></div>
	            	</div>
	            	<div class="gritter-bottom"></div>
	            </div>
	        ';
	    }

	?>

	<div class="main-container">
		<div style="margin-top:8em;"></div>
		<div class="main-content">
				<div class="col-sm-4 col-sm-offset-4">
					<div class="login-container">
						<div class="center logo-empresa-login"></div>
						<div class="space-6"></div>
						<div class="position-relative">
						<?php echo $this->content; ?>
						</div><!-- /.position-relative -->
					</div>
				</div><!-- /.col -->
		</div><!-- /.main-content -->
	</div><!-- /.main-container -->

<style>
	.logo-empresa-login{
		height: 60px;
		background-image: url(<?php echo $this->Theme()['logo_login']?>);
		width: 330px;
	    overflow: hidden;
	    background-size: 200px;
	    height: 60px;
	    background-position: top center;
	    background-repeat: no-repeat;
	}
</style>


</body>
</html>