<?php echo $this->doctype(); 
    if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <base href="<?php echo $this->serverUrl().$this->basePath()."/";?>" />
        <?php echo $this->headTitle($this->Theme()['titulo_panel'])->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
       <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'images/favicon.png', 'href' => $this->basePath() . '/images/favicon.png'))
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('css/ace-fonts.css'))
            ->appendStylesheet($this->basePath('css/ace.min.css'))

            ->appendStylesheet($this->basePath('reproductor/dist/plyr.css'))
            /*->appendStylesheet($this->basePath('reproductor/dist/demo.css'))*/

            ->appendStylesheet($this->basePath('css/tutorialtheme.min.css'))

            

            ->appendStylesheet($this->basePath($this->Theme()['ruta_theme']))
        ?>

        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery.min.js'))
            ->appendFile($this->basePath('js/ace-extra.min.js'))
            ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 8',))
            ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 8',))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/jquery-ui.min.js'))
            ->appendFile($this->basePath('js/jquery.ui.touch-punch.min.js'))
            ->appendFile($this->basePath('js/ace-elements.min.js'))
            ->appendFile($this->basePath('js/ace.min.js'))
            ->appendFile($this->basePath('js/ace/ace.onpage-help.js'))
            ->appendFile($this->basePath('js/rainbow.js'))
            ->appendFile($this->basePath('/js/jqGrid/i18n/grid.locale-en.js'))
        ?>
    </head>
    <body>
            <!-- #section:basics/navbar.layout -->
    <div id="navbar" class="navbar navbar-default">
        <script type="text/javascript">
            try{ace.settings.check('navbar' , 'fixed')}catch(e){}
        </script>

        <div class="navbar-container" id="navbar-container">
            <!-- #section:basics/sidebar.mobile.toggle -->
            <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
                <span class="sr-only">Toggle sidebar</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>
            </button>

            <!-- /section:basics/sidebar.mobile.toggle -->
            <div class="navbar-header pull-left">
                <!-- #section:basics/navbar.layout.brand -->
                <a href="#" class="navbar-brand" style="padding:3px 0 0 0;">
                    <!--<small><i class="fa fa-leaf"></i> Edificio OK</small>-->
                    <img src="<?php echo $this->basePath($this->Theme()['logo_panel'] ) ;?>" width="135px">
                </a>

                <!-- /section:basics/navbar.layout.brand -->

                <!-- #section:basics/navbar.toggle -->

                <!-- /section:basics/navbar.toggle -->
            </div>


            <!-- #section:basics/navbar.dropdown -->
            <div class="navbar-buttons navbar-header pull-right" role="navigation" >
                <ul class="nav ace-nav">
                    <!-- #section:basics/navbar.user_menu -->
                    

                    <!-- /section:basics/navbar.user_menu -->
                </ul>
            </div>
            <!-- /section:basics/navbar.dropdown -->
        </div><!-- /.navbar-container -->
    </div>
        <div class="container" style="margin-top:40px;">
            <?php echo $this->content; ?>
        </div>
        <div class="footer" style="background-color:#55555;clear:both;">
            <div class="footer-inner">
                <center>
                    <span class="bigger-120">
                        <img src="images/marca_edificiook.png" alt="" height="30" width="100">
                        <small>Derechos reservados</small> © <?php echo date('Y'); ?>
                    </span>
                    <span class="action-buttons">
                        <a href="https://www.facebook.com/edificiook">
                            <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                        </a>
                    </span>
                </center>
            </div>
        </div>
            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse display">
                <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
            </a>
    </body>

    <!-- Scripts -->
    <?php 
    //$this->headScript()
        /*->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))*/
    ?>

    <?php //$this->inlineScript()
            //    ->appendFile($this->basePath('/script/application/main.js?t='.time()),'text/javascript')
            ?>
            <?php echo $this->inlineScript() ?>
</html>