<?php echo $this->doctype(); 
    if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->serverUrl().$this->basePath()."/";?>" />
    <?php echo $this->headTitle($this->Theme()['titulo_panel'])->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ->appendName( 'autor' ,  'KND S.A.C')
    ->appendName( 'keywords' ,  '')

    ?>
    <!-- bootstrap & fontawesome -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'images/favicon.png', 'href' => $this->basePath() . '/images/favicon.png'))
    ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
    ->appendStylesheet($this->basePath('css/font-awesome.min.css?'.time()))
    ->appendStylesheet($this->basePath('css/chosen.css'))
    ->appendStylesheet('https://cdn.jsdelivr.net/sweetalert2/6.4.3/sweetalert2.css')
    /*jqgrid*/
    ->appendStylesheet($this->basePath('css/jquery-ui.min.css'))
    ->appendStylesheet($this->basePath('css/datepicker.css'))
    ->appendStylesheet($this->basePath('css/bootstrap-timepicker.css'))
    ->appendStylesheet($this->basePath('css/bootstrap-datetimepicker.css'))
    ->appendStylesheet($this->basePath('css/ui.jqgrid.css'))
    ->appendStylesheet($this->basePath('css/ace-fonts.css'))
    ->appendStylesheet($this->basePath('css/ace.min.css'))
    ->appendStylesheet($this->basePath('css/jquery.gritter.css'))
    ->appendStylesheet($this->basePath('css/ace-skins.min.css'))
    ->appendStylesheet($this->basePath('css/ace-rtl.min.css'))
    ->appendStylesheet($this->basePath('css/ace.onpage-help.css'))
    ->appendStylesheet($this->basePath('css/jqgrid-style.css'))
    ->appendStylesheet($this->basePath('css/style.css'))
    ->appendStylesheet($this->basePath($this->Theme()['ruta_theme']."?".time()))
    
    ?>
</head>
<body class="no-skin">
<!-- page specific plugin scripts -->
    <!-- Scripts -->
    <?php echo $this->headScript()
    ->appendFile($this->basePath('js/jquery.min.js'))
    ->appendFile($this->basePath('js/ace-extra.min.js'))
    ->appendFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 8',))
    ->appendFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 8',))
    ->appendFile($this->basePath('js/bootstrap.min.js'))
    ->appendFile($this->basePath('js/jquery-ui.min.js'))
    ->appendFile($this->basePath('js/jquery.ui.touch-punch.min.js'))
    ->appendFile($this->basePath('js/chosen.jquery.min.js'))
    ->appendFile($this->basePath('js/jquery.easypiechart.min.js'))
    ->appendFile($this->basePath('js/jquery.sparkline.min.js'))
    ->appendFile($this->basePath('js/flot/jquery.flot.min.js'))
    ->appendFile($this->basePath('js/flot/jquery.flot.pie.min.js'))
    ->appendFile($this->basePath('js/flot/jquery.flot.resize.min.js'))
    ->appendFile($this->basePath('js/ace-elements.min.js'))
    ->appendFile($this->basePath('js/ace.min.js'))
    ->appendFile($this->basePath('js/ace/ace.onpage-help.js'))
    ->appendFile($this->basePath('js/rainbow.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-datepicker.min.js'))
    ->appendFile($this->basePath('js/date-time/moment.min.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-datepicker.es.min.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-timepicker.min.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-datetimepicker.min.js'))

    ->appendFile($this->basePath('js/jquery.maskedinput.min.js'))
    ->appendFile($this->basePath('js/jquery.price_format.2.0.min.js'))

    ->appendFile($this->basePath('js/language/generic.js'))
    ->appendFile($this->basePath('js/language/html.js'))
    ->appendFile($this->basePath('js/language/css.js'))
    ->appendFile($this->basePath('js/language/javascript.js'))
    ->appendFile($this->basePath('/js/jqGrid/jquery.jqGrid.min.js'))
    ->appendFile($this->basePath('/js/jqGrid/i18n/grid.locale-en.js'))
    ->appendFile($this->basePath('js/jquery.gritter.min.js'))
    ->appendFile($this->basePath('js/tinymce/tinymce.min.js'))
    ->appendFile($this->basePath('js/tinymce/es.js'))
    ->appendFile($this->basePath('js/jquery.validate.min.js'))
    ->appendFile($this->basePath('js/masonry/masonry.pkgd.min.js'))
    ->appendFile($this->basePath('js/jquery.slimscroll.js'))
    ->appendFile('https://cdn.jsdelivr.net/sweetalert2/6.4.3/sweetalert2.js')

    ?>

    <!-- #section:basics/navbar.layout -->
    <div id="navbar" class="navbar navbar-default">
        <script type="text/javascript">
            try{ace.settings.check('navbar' , 'fixed')}catch(e){}
        </script>

        <div class="navbar-container" id="navbar-container">
            <!-- #section:basics/sidebar.mobile.toggle -->
            <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
                <span class="sr-only">Toggle sidebar</span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>

                <span class="icon-bar"></span>
            </button>

            <!-- /section:basics/sidebar.mobile.toggle -->
            <div class="navbar-header pull-left">
                <!-- #section:basics/navbar.layout.brand -->
                <a href="#" class="navbar-brand" style="padding:3px 0 0 0;">
                    <!--<small><i class="fa fa-leaf"></i> Edificio OK</small>-->
                    <img src="<?php echo $this->basePath($this->Theme()['logo_panel'] ) ;?>" width="135px">
                </a>

                <!-- /section:basics/navbar.layout.brand -->

                <!-- #section:basics/navbar.toggle -->

                <!-- /section:basics/navbar.toggle -->
            </div>


            <!-- #section:basics/navbar.dropdown -->
            <div class="navbar-buttons navbar-header pull-right" role="navigation" >
                <ul class="nav ace-nav">
                        
                    <!--TOOLS-->
                    <li class="menu_tools dropdown tools fondo_color">

                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-expanded="false" style="line-height: 53px;">
                              <i class="fa fa-cog" data-toggle="tooltip" data-placement="left" title="Herramientas" style="font-size: 25px;"></i>
                            </a>

                            <ul class="dropdown-menu p-0 dropdown-menu-lg">
                                        <!--<li class="notifi-title"><span class="label label-default pull-right">New 3</span>Notification</li>-->
                                        <li class="list-group notification-list">
                                           <div class="slimscroll">
                                               <!-- list item-->
                                               <a href="javascript:void(0);" class="list-group-item hidden">
                                                  <div class="media" onClick="ToolsPanel.generateCrep()">
                                                     <div class="media-left p-r-10">
                                                        <em class="fa fa-university bg-primary"></em>
                                                     </div>
                                                     <div class="media-body">
                                                        <h5 class="media-heading">Archivo de recaudación BCP</h5>
                                                        <p class="m-0">
                                                            <small>Generar CREP</small>
                                                        </p>
                                                     </div>
                                                  </div>
                                               </a>

                                               <!-- list item-->
                                               <a href="javascript:void(0);" class="list-group-item">
                                                  <div class="media" onClick="ToolsPanel.viewImportarCrep()">
                                                     <div class="media-left p-r-10">
                                                        <em class="fa fa-university bg-primary"></em>
                                                     </div>
                                                     <div class="media-body">
                                                        <h5 class="media-heading">Cobranzas de recaudación</h5>
                                                        <p class="m-0">
                                                            <small>Importar CREP</small>
                                                        </p>
                                                     </div>
                                                  </div>
                                               </a>


                                           </div>
                                        </li>
                                    </ul>
                                    

                                    <script>
                                        $(".notification-list").slimScroll({
                                            color:"#9a437a"
                                        });
                                    </script>

                            

                          </li>
                    <!---->

                    <li class="purple hidden">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="ace-icon fa fa-tasks"></i>
                            <span class="badge badge-grey">4</span>
                        </a>

                        <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                            <li class="dropdown-header">
                                <i class="ace-icon fa fa-check"></i>
                                4 Tasks to complete
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">Software Update</span>
                                        <span class="pull-right">65%</span>
                                    </div>

                                    <div class="progress progress-mini">
                                        <div style="width:65%" class="progress-bar"></div>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">Hardware Upgrade</span>
                                        <span class="pull-right">35%</span>
                                    </div>

                                    <div class="progress progress-mini">
                                        <div style="width:35%" class="progress-bar progress-bar-danger"></div>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">Unit Testing</span>
                                        <span class="pull-right">15%</span>
                                    </div>

                                    <div class="progress progress-mini">
                                        <div style="width:15%" class="progress-bar progress-bar-warning"></div>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">Bug Fixes</span>
                                        <span class="pull-right">90%</span>
                                    </div>

                                    <div class="progress progress-mini progress-striped active">
                                        <div style="width:90%" class="progress-bar progress-bar-success"></div>
                                    </div>
                                </a>
                            </li>

                            <li class="dropdown-footer">
                                <a href="#">
                                    See tasks with details
                                    <i class="ace-icon fa fa-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="purple hidden">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                            <span class="badge badge-important">8</span>
                        </a>

                        <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                            <li class="dropdown-header">
                                <i class="ace-icon fa fa-exclamation-triangle"></i>
                                8 Notifications
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
                                            New Comments
                                        </span>
                                        <span class="pull-right badge badge-info">+12</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <i class="btn btn-xs btn-primary fa fa-user"></i>
                                    Bob just signed up as an editor ...
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="btn btn-xs no-hover btn-success fa fa-shopping-cart"></i>
                                            New Orders
                                        </span>
                                        <span class="pull-right badge badge-success">+8</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="#">
                                    <div class="clearfix">
                                        <span class="pull-left">
                                            <i class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
                                            Followers
                                        </span>
                                        <span class="pull-right badge badge-info">+11</span>
                                    </div>
                                </a>
                            </li>

                            <li class="dropdown-footer">
                                <a href="#">
                                    See all notifications
                                    <i class="ace-icon fa fa-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="purple hidden">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <i class="ace-icon fa fa-envelope icon-animated-vertical"></i>
                            <span class="badge badge-success">5</span>
                        </a>

                        <ul class="dropdown-menu-right dropdown-navbar dropdown-menu navbar-pink dropdown-caret dropdown-close">
                            <li class="dropdown-header">
                                <i class="ace-icon fa fa-envelope-o"></i>
                                5 Messages
                            </li>

                            <li class="dropdown-content">
                                <ul class="dropdown-menu dropdown-navbar">
                                    <li>
                                        <a href="#">
                                            <img src="avatars/avatar.png" class="msg-photo" alt="Alex's Avatar" />
                                            <span class="msg-body">
                                                <span class="msg-title">
                                                    <span class="blue">Alex:</span>
                                                    Ciao sociis natoque penatibus et auctor ...
                                                </span>

                                                <span class="msg-time">
                                                    <i class="ace-icon fa fa-clock-o"></i>
                                                    <span>a moment ago</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <img src="avatars/avatar3.png" class="msg-photo" alt="Susan's Avatar" />
                                            <span class="msg-body">
                                                <span class="msg-title">
                                                    <span class="blue">Susan:</span>
                                                    Vestibulum id ligula porta felis euismod ...
                                                </span>

                                                <span class="msg-time">
                                                    <i class="ace-icon fa fa-clock-o"></i>
                                                    <span>20 minutes ago</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <img src="avatars/avatar4.png" class="msg-photo" alt="Bob's Avatar" />
                                            <span class="msg-body">
                                                <span class="msg-title">
                                                    <span class="blue">Bob:</span>
                                                    Nullam quis risus eget urna mollis ornare ...
                                                </span>

                                                <span class="msg-time">
                                                    <i class="ace-icon fa fa-clock-o"></i>
                                                    <span>3:15 pm</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <img src="avatars/avatar2.png" class="msg-photo" alt="Kate's Avatar" />
                                            <span class="msg-body">
                                                <span class="msg-title">
                                                    <span class="blue">Kate:</span>
                                                    Ciao sociis natoque eget urna mollis ornare ...
                                                </span>

                                                <span class="msg-time">
                                                    <i class="ace-icon fa fa-clock-o"></i>
                                                    <span>1:33 pm</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>

                                    <li>
                                        <a href="#">
                                            <img src="avatars/avatar5.png" class="msg-photo" alt="Fred's Avatar" />
                                            <span class="msg-body">
                                                <span class="msg-title">
                                                    <span class="blue">Fred:</span>
                                                    Vestibulum id penatibus et auctor  ...
                                                </span>

                                                <span class="msg-time">
                                                    <i class="ace-icon fa fa-clock-o"></i>
                                                    <span>10:09 am</span>
                                                </span>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="dropdown-footer">
                                <a href="inbox.html">
                                    See all messages
                                    <i class="ace-icon fa fa-arrow-right"></i>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <!-- #section:basics/navbar.user_menu -->
                    <li class="fondo_color">
                        <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                            <img class="nav-user-photo" src="avatars/user.lokjikiole.png" alt="" style="background-color:#FFFFFF;" />
                            <span class="user-info">
                                <small>Bienvenido ,</small>
                                <?php echo $this->USERNAME_SESSION_ACTIVA;?>
                            </span>

                            <i class="ace-icon fa fa-caret-down"></i>
                        </a>

                        <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                            <li>
                                <a href="javascript:void();">
                                    <i class="ace-icon fa fa-cog"></i>
                                    Settings
                                </a>
                            </li>

                            <li>
                                <a href="javascript:void();">
                                    <i class="ace-icon fa fa-user"></i>
                                    Profile
                                </a>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <a href="<? echo $this->url('logout')?>">
                                    <i class="ace-icon fa fa-power-off"></i>
                                    Logout
                                </a>
                            </li>
                        </ul>
                    </li>

                    <!-- /section:basics/navbar.user_menu -->
                </ul>
            </div>
            <!-- /section:basics/navbar.dropdown -->
        </div><!-- /.navbar-container -->
    </div>

    <div id="sidebar" class="sidebar responsive">
        <script type="text/javascript">
            try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
        </script>

        <div class="sidebar-shortcuts" id="sidebar-shortcuts" style="">
            <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
                <button class="btn btn-success">
                    <i class="ace-icon fa fa-signal"></i>
                </button>

                <button class="btn btn-info" onClick="abrirModal();">
                    <i class="ace-icon fa fa-pencil"></i>
                </button>
				<!-- <span><a href="javascript:void();">Nuevo edificio</a></span> -->
                <!-- #section:basics/sidebar.layout.shortcuts -->
                <button class="btn btn-warning">
                    <i class="ace-icon fa fa-users"></i>
                </button>

                <button class="btn btn-danger">
                    <i class="ace-icon fa fa-cogs"></i>
                </button>

                <!-- /section:basics/sidebar.layout.shortcuts -->
            </div>

            <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
                <span class="btn btn-success"></span>

                <span class="btn btn-info"></span>

                <span class="btn btn-warning"></span>

                <span class="btn btn-danger"></span>
            </div>
        </div><!-- /.sidebar-shortcuts -->
        <ul class="nav nav-list">
            <li class="<?php echo ($this->ROUTENAME)=='home'? 'active':(($_SERVER['REQUEST_URI']==$this->RAIZPROYECTO.'ue')?'active':''); ?>">
                <a href="<?php  echo ( ($this->ROUTENAME)=='ue')?$this->url('home-ue'):$this->url('home'); ?>">
                    <i class="menu-icon fa fa-tachometer"></i>
                    <span class="menu-text"><?php echo ($this->ROUTENAME=='ue' ? 'Edificio':'dashboard'); ?></span>
                </a>
                
                <b class="arrow"></b>

            </li>
            <?php
            if($this->MENU){
                $i=0;
                while ($i<count($this->MENU)) {
                    $currentGrupoMenu = $this->MENU[$i]['grupomenu'];
                    if ($currentGrupoMenu == $this->MENU[$i]['menu']){
                        //escribir menu grupo - nuevo (unico).
                        $estadoClassMenu='';
                        if($this->RAIZPROYECTO.$this->MENU[$i]['url']==$_SERVER['REQUEST_URI']){
                            $estadoClassMenu='active';
                        }
                        echo '<li class="'.$estadoClassMenu.'">
                                        <a href="'.$this->RAIZPROYECTO.$this->MENU[$i]['url'].'">
                                            <i class="menu-icon glyphicon glyphicon-home"></i>
                                            <span class="menu-text">'.$currentGrupoMenu.'</span>
                                        </a>
                                        <b class="arrow"></b>
                                   </li>';
                    } else {
                        //escribir menu grupo - nuevo
                        $estadoClassGrupoMenu='';
                        if($this->MENU[$i]['route']==$this->ROUTENAME){
                            $estadoClassGrupoMenu='active open';
                        }

                        echo '<li class="'.$estadoClassGrupoMenu.'">
                                    <a href="" class="dropdown-toggle">
                                        <i class="menu-icon fa fa-folder"></i>
                                        <span class="menu-text">'.$currentGrupoMenu.'</span>
                                        <b class="arrow fa fa-angle-down"></b>
                                    </a>
                                    <b class="arrow"></b>
                                    <ul class="submenu">';

                        while (true) {
                            if ($currentGrupoMenu == $this->MENU[$i]['grupomenu']) {
                                //Escribir menu
                                $estadoClassMenu='';
                                if($this->RAIZPROYECTO.$this->MENU[$i]['url']==$_SERVER['REQUEST_URI']){
                                    $estadoClassMenu='active';
                                }
                                echo '<li class="'.$estadoClassMenu.'">
                                            <a href="'. $this->RAIZPROYECTO.$this->MENU[$i]['url'].'">
                                               <i class="menu-icon fa fa-caret-right"></i>'.$this->MENU[$i]['menu'].'
                                            </a>
                                            <b class="arrow"></b>
                                          </li>';
                                $i++;
                                if($i >= count($this->MENU) ){
                                    break;
                                }
                            } else {
                                $i--;
                                break;
                            }
                        }

                        echo '</ul></li>';
                    }
                    $i++;
                }
            }
            ?>
                <!-- #section:basics/sidebar.layout.minimize -->
                <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
                    <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
                </div>

                <!-- /section:basics/sidebar.layout.minimize -->
                <script type="text/javascript">
                    try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
                </script>
            </div>

            <div class="main-content">

                <!-- #section:basics/content.breadcrumbs -->
                <div class="breadcrumbs" id="breadcrumbs">
                    <script type="text/javascript">
                        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
                    </script>

                    <!--<ul class="breadcrumb">
                        <li>
                            <i class="ace-icon fa fa-home home-icon"></i>
                            <a href="#">Inicio</a>
                        </li>
                        <li class="active">Panel</li>
                    </ul>--><!-- /.breadcrumb -->
                  <ul class="breadcrumb">
                      <?php
                      $breadcrumb=$this->navigation('navigation')->breadcrumbs()->render();
                      if($breadcrumb!=''){
                          echo $breadcrumb;
                      }else{
                          switch ($this->ROUTENAME){
                              case 'edificio':
                                  echo '<li>
                                        <i class="ace-icon fa fa-home home-icon"></i>
                                        <a href="'.$this->url('edificio').'">Edificio</a>
                                    </li>';
                                  break;
                              case 'home':
                                  echo '<li>
                                        <i class="ace-icon fa fa-tachometer"></i>
                                        <a href="'.$this->url('home').'">Dashboard</a>
                                    </li>';
                                  break;
                              default:
                                  echo '<li>
                                        <i class="ace-icon fa fa-tachometer"></i>
                                        <a href="'.$this->url('home').'">Dashboard</a>
                                    </li>';
                          }
                      }

                      ?>
                  </ul>
                    <!-- #section:basics/content.searchbox -->
                    
                    <div class="nav-search" id="nav-search" style="">
                        <form class="form-search">
                            <!-- <span class="input-icon">
                                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                                <i class="ace-icon fa fa-search nav-search-icon"></i>
                            </span> -->
							
                            <div style="display: inline-block; width: 250px;">
								
                                <select id="chEdificio" data-placeholder="Seleccione el edificio...">
                                    <option value="">  </option>
                                    <?php
                                        if(count($this->EDIFICIOS)>0){
                                            foreach ($this->EDIFICIOS as $key => $value) {
                                                if($value['id']==$this->EDIFICIO_SELECCIONADO){
                                                    echo '<option value="'.$value['id'].'" selected>'.$value['nombre'].'</option>';
                                                }else{
                                                    echo '<option value="'.$value['id'].'">'.$value['nombre'].'</option>';
                                                }
                                            }
                                        }
                                    ?>
                                </select>
                            </div>
                        </form>
                    </div><!-- /.nav-search -->

                    <!-- /section:basics/content.searchbox -->
                </div>
                <div class="page-content">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <div class="footer" style="background-color:#55555;clear:both;">
                <div class="footer-inner">
                    <div class="footer-content">
                        <span class="bigger-120">
                            <img src="images/marca_edificiook.png" alt="" height="30" width="100">
                            <small>Derechos reservados</small> © <?php echo date('Y'); ?>
                        </span>
                        <span class="action-buttons">
                            <a href="https://www.facebook.com/edificiook" target="_blank">
                                <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse display">
                <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
            </a>

            <!--MODAL GENERATE CREP-->
            <div class="modal fade" id="m_recaudacion_bcp" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Archivo de recaudación BCP</h4>
                        </div>
                        <div class="r_success">
                            <div class="modal-body">
                                <i class="fa fa-refresh fa-spin fa-3x fa-fw"></i><br>
                                <p>Generando archivo</p>
                            </div>
                        </div>
                        <div class="r_error hidden"></div>
                    </div>
                </div>
            </div>
            <!---->

            <!--MODAL MENSAJE CREP-->
            <div class="modal fade" id="m_message_crep" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">Archivo de recaudación BCP</h4>
                        </div>
                        <div class="modal-body">
                            <p>Seleccione la extensión:</p>
                            <div class="radio">
                                <label>
                                    <input name="btncompress" type="radio" class="ace" value="rar" checked="">
                                    <span class="lbl"> .rar (Windows)</span>
                                </label>
                                <label>
                                    <input name="btncompress" type="radio" class="ace" value="gzip">
                                    <span class="lbl"> .gzip (Linux)</span>
                                </label>
                            </div>  
                        </div>
                        <div class="modal-footer">
                            <div class="center">
                                <button type="button" class="btn btn-success btn-sm" data-dismiss="modal" onClick="ToolsPanel.downloadCrep()"><i class="ace-icon fa fa-check bigger-110"></i> Aceptar</button>
                                <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal"><i class="ace-icon fa fa-times bigger-110"></i> Cerrar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!---->
            <div class="modal fade" id="nuevoEdificio" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
							<h4 class="modal-title">Nuevo edificio</h4>
						</div>
						<div class="modal-body" style="position: relative;">
							<div class="row">
								<div class="col-md-8">
									<input type="text" name="edificio_nombre" id="edificio_nombre" placeholder="Nombre del edificio" class="form-control">
								</div>
								<div class="col-md-4">
									<button type="button" class="btn btn-primary btn-sm" onclick="nuevoedificio();">Registrar</button>
								</div>
							</div>
						</div>
					</div>
				</div>						
			</div>
            <!--MODAL IMPORTAR CREP-->
            <div class="modal fade" id="m_cobranza_recaudacion" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">Cobranza de recaudación</h4>
                        </div>
                        <div class="modal-body" style="position:relative;">
                        
                        <div class="loadCrep hidden">
                            <div style="width: 100%;height: 100%;background: rgba(221, 221, 221, 0.57);position: absolute;top: -1px;left: 0;z-index: 100;"></div>
                            <div class="spinner" style="opacity: inherit;">
                              <div class="bounce1"></div>
                              <div class="bounce2"></div>
                              <div class="bounce3"></div>
                            </div>
                        </div>


                            <div class="row">
                                <form class="frm_file_crep">
                                    <div class="col-md-12">
                                        <div class="left" style="border-bottom: 1px solid #ddd;padding-bottom: 5px;font-size: 14px;margin-bottom: 7px;">
                                            Archivo de recaudación: <button type="button" id="btnShowModal" class="btn btn-xs btn-primary" style="font-size: 13px;">Adjuntar</button>
                                        </div>
                                        <div id="btn_tools" class="right hidden">
                                            <button type="button" class="btn btn-white btn-sm btn-primary" onclick="ToolsPanel.transferirCrep()">Registrar</button>
                                            <input type="file" name="filecrep" id="idcrep" class="hidden" onchange="ToolsPanel.getCrep(event)">
                                            <button type="button" class="btn btn-white btn-sm btn-primary" onclick="ToolsPanel.deleteCrep();">
                                              <i class="ace-icon fa fa-trash-o" style="font-size: 22px;"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>

                                <div class="col-xs-12" style="height: 300px;overflow-x: hidden;">
                                    <table id="table_grep" class="table table-striped table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="center" width="40">
                                                    <label class="position-relative hidden">
                                                        <input type="checkbox" class="ace">
                                                        <span class="lbl"></span>
                                                    </label>
                                                </th>
                                                <th width="50"></th>
                                                <th>Archivo</th>
                                                <th>Fecha de movimiento</th>
                                                <th>N° de cuenta</th>
                                                <th>Edificio</th>
                                                <th>Resultado</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer hidden"></div>
                    </div>
                </div>
            </div>
            <!---->
<script>

function abrirModal() {
	$("#nuevoEdificio").modal('show');
}

function nuevoedificio() {

	var nombre = $("#edificio_nombre").val();

	$.post('/edificio/nuevo', {
		nombre: nombre
	}, function(data) {
		console.log(data);
		// $("#nuevoEdificio").modal('hide');
		// location.href = "<?= $this->basePath(); ?>";
	});
}
</script>
            <?php $this->inlineScript()
                ->appendFile($this->basePath('/script/application/main.js?'.time()),'text/javascript')
            ?>
            <?php echo $this->inlineScript() ?>
        </body>
        </html>
