<style>
	#t_grid-visitas{
		margin-top: 5px;
		height: 35px;
	}
	.form-group{
		margin-bottom: 0px;
	}
	.bootstrap-timepicker-widget{
		z-index: 10000!important;
	}
</style>

<div class="row">
	<div class="col-xs-12">
		<div class="table-header">
			<div class="row">
				<div class="col-xs-4">Visitas</div>
				<div class="col-xs-8">
					<div id="btn-actions-default"class="btn-group pull-right" role="group" aria-label="...">
						<button type="button" id="btnDescargar" class="btn btn-default btn-sm btnOpe hidden" onclick="rowAction.descargar();">
							<i class="ace fa fa-cloud-download"></i>
							<span>Descargar</span>
						</button>
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="rowAction.new()">
							<i class="glyphicon glyphicon-file"></i>
							<span>Nuevo</span>
						</button>
					</div>
					<div id="btn-actions" class="btn-group pull-right hidden" role="group" aria-label="...">
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="rowAction.view()">
					  		<i class="fa fa-eye"></i>
							<span>Ver</span>
					  	</button>
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="rowAction.edit()">
							<i class="glyphicon glyphicon-pencil"></i>
							<span>Editar</span>
						</button>
					  	<button type="button" class="btn btn-default btn-sm btnOpe" onclick="rowAction.del()">
					  		<i class="glyphicon  glyphicon-trash"></i>
							<span>Eliminar</span>
					  	</button>
					</div>
				</div>
			</div>
		</div>
		<table id="grid-visitas"></table>
		<div id="grid-pager"></div>
	</div>
</div>

<!-- FORMULARIO DE VISITAS -->
<div class="modal fade" id="myModalVisitas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
  	<form id="validate" class="frmVisitas">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="exampleModalLabel">VISITAS</h4>
	      </div>
	      <div class="modal-body">
				
				<div class="row">
					
					<div class="col-sm-12 margin-bottom-10">
						
			      		<div class="form-group">
							<div>
								<div class="col-sm-6">
									<label class="control-label no-padding-right"> Unidad </label>
									<div>
										<select class="form-control chosen-select" name="selUnidad" id="unidad">
											<option disabled="" selected="select">Seleccione...</option>
											<?php foreach($this->listarUnidad as $unidad): ?>
												<option value="<?php echo $unidad['uni_in_cod']; ?>"><?php echo $unidad['descrip']; ?></option>
											<?php endforeach; ?>
										</select>
									</div>
								</div>
							</div>

							<div>							
								<div class="col-sm-6">
									<!--<label class="control-label no-padding-right"> Tipo </label>
									<div>
										<select class="form-control chosen-select" name="selTipo">
											<option disabled="">Seleccione...</option>
											<option value="VISITA" selected="select">VISITA</option>
						                    <option value="CONTRATISTA">CONTRATISTA</option>
						                    <option value="FRECUENTE">FRECUENTE</option>
						                    <option value="EVENTUAL">EVENTUAL</option>
						                    <option value="OTROS">OTROS</option>
										</select>
									</div>-->
								</div>
							</div>
						</div>

					</div>

					<div class="col-sm-12 margin-bottom-10">
						
						<div class="form-group">
							<div class="col-sm-6">
								<label class="control-label no-padding-right"> Propietario </label>
								<div>
									<input type="text" name="txtPropietario" id="propietario" class="col-xs-10 col-sm-12" readonly="" />
									<input type="text" name="txtCodPropietario" id="codPropietario" class="hidden" />
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-6">
								<label class="control-label no-padding-right"> Residente </label>
								<div>
									<input type="text" name="txtResidente" id="residente" class="col-xs-10 col-sm-12" readonly="" />
									<input type="text" name="txtCodResidente" id="codResidente" class="hidden" />
								</div>
							</div>
						</div>

					</div>

					<div class="col-sm-12 margin-bottom-10">
						
						<!--<div class="form-group">
							<div class="col-sm-4">
								<label class="control-label no-padding-right"> Fecha </label>
								<div>
									<input type="text" name="txtFecha" class="col-xs-10 col-sm-12" readonly="" value="<?php echo date('Y/m/d'); ?>" />
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-4">
								<label class="control-label no-padding-right"> Hora </label>
								<div>
									<input type="text" name="txtHora" class="col-xs-10 col-sm-12" id="hora" readonly="" />
								</div>
							</div>
						</div>-->

						<div class="form-group">
							<div>
								<div class="col-sm-6">
									<label class="control-label no-padding-right"> Tipo </label>
									<div>
										<select class="form-control chosen-select" name="selTipo" id="tipo">
											<option disabled="">Seleccione...</option>
											<option value="VISITA" selected="select">VISITA</option>
						                    <option value="CONTRATISTA">CONTRATISTA</option>
						                    <option value="FRECUENTE">FRECUENTE</option>
						                    <option value="EVENTUAL">EVENTUAL</option>
						                    <option value="OTROS">OTROS</option>
										</select>
									</div>
								</div>
							</div>
							<div>
								<div class="col-sm-6">
									<label class="control-label no-padding-right"> Importancia</label>
									<div>
										<select class="form-control" name="selImportancia" id="importancia">
											<option disabled="" selected="select">Seleccione...</option>
											<option value="ALTA" >ALTA</option>
					                        <option value="INTERMEDIA" >INTERMEDIA</option>                    
					                        <option value="BAJA">BAJA</option>
										</select>
									</div>
								</div>
							</div>
						</div>

					</div>


					<div class="col-sm-12 margin-bottom-10">
						
						<div class="form-group">
							<div class="col-sm-4">
								<label class="control-label no-padding-right"> Asunto </label>
								<div>
									<input type="text" name="txtAsunto" class="col-xs-10 col-sm-12" />
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-sm-4">
								<label class="control-label no-padding-right"> Fecha </label>
								<div>
									<input type="text" name="txtFecha" id="fecha" value="<?php echo date('d/m/Y'); ?>" class="col-xs-10 col-sm-12" />
								</div>
							</div>
						</div>

						<div class="form-group">
							<div>
								<div class="col-sm-4">
									<label class="control-label no-padding-right"> Hora </label>
									<div class="input-group bootstrap-timepicker">
										<input id="hora" type="text" class="form-control" name="txtHora" />
										<span class="input-group-addon">
											<i class="fa fa-clock-o bigger-110"></i>
										</span>
									</div>
								</div>
							</div>
						</div>

					</div>

					<div class="col-sm-12 margin-bottom-10">
						
						<div class="form-group">
							<div class="col-sm-12">
								<label class="control-label no-padding-right"> Empresa </label>
								<div>
									<input type="text" name="txtEmpresa" class="col-xs-10 col-sm-12" />
								</div>
							</div>
						</div> 

						<div class="form-group">
							<div class="col-sm-12">
								<label class="control-label no-padding-right"> Ocurrencia </label>
								<div>
									<textarea class="form-control" rows="3" name="txtOcurrencia"></textarea>
								</div>
							</div>
						</div>

					</div>

				</div>
				

	      </div>
	      <div class="modal-footer">
	        <button type="submit" id="btnAddIngreo" class="btn btn-success btn-sm">
				<i class="ace-icon fa fa-floppy-o bigger-110"></i> Guardar
			</button>
			<button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
				<i class="ace-icon fa fa-times bigger-110"></i> Cerrar
			</button>
	      </div>
	    </div>
    </form>
  </div>
</div>

<?php
	$this->inlineScript()
	    ->appendFile($this->basePath('/script/ue/visitas.js'),'text/javascript')
?>
