<style>
	.profile-user-info-striped .profile-info-name {
	    color: #000;
	    background-color: #EEEEEE;
	}
	.profile-user-info-striped{
		border: 1px solid #eee;
	}
	.p-title{
		border-bottom: 1px solid #CCC;
		margin-bottom: 10px;
		padding-bottom: 2px;
	}
	.profile-info-name{
		width: 132px;
	}
	.td-right{
		text-align: right;
	}
</style>

<div class="row">
	<div class="col-xs-12">
		<div class="table-header" id="jqgrid">
			<div class="row">
				<div class="col-xs-4">Pagos</div>
				<div class="col-xs-8">
					<div class="btn-group pull-right margin-top-0" role="group" aria-label="...">
						<span>Unidad: </span>
						<select id="unidad">
							<?php 
								if(isset($this->listarUnidad)){
									foreach($this->listarUnidad as $unidad){
										echo '<option value="'.$unidad['id'].'">'.$unidad['unidadNombre'].'</option>';
									}
								}else{
									echo '<option value="0">No hay unidades</option>';
								}
							?>
						</select>
					</div>
					<div id="btn-actions" class="btn-group pull-right" role="group" aria-label="...">
						<button type="button" class="btn btn-default btn-sm btnOpe" onclick="DateControls.backYear()">
					  		<i class="ace-icon fa fa-angle-left biger-150"></i>
					  	</button>
					  	<button  type="button" class="btn btn-default btn-sm btnOpe">
					  		<span id="currentYear"><?php echo date('Y');?></span>
					  	</button>
					  	<button type="button" class="btn btn-default btn-sm btnOpe" onclick="DateControls.nextYear()">
					  		<i class="ace-icon fa fa-angle-right"></i>
					  	</button>
					</div>
				</div>
			</div>
		</div>
		<div style="width:100%;">
			<table id="tblPagos" class="table table-striped table-hover">
			 	<thead>
			 		<tr>
			 			<th width="5"></th>
			 			<th width="50"><i class="ace-icon fa fa-caret-right blue"></i> Mes</th>
			 			<th width="50" class="center"><i class="ace-icon fa fa-caret-right blue"></i> Total</th>
			 			<th width="50" class="center"><i class="ace-icon fa fa-caret-right blue"></i> Pagado</th>
			 			<th width="50" class="center"><i class="ace-icon fa fa-caret-right blue"></i> Debe</th>
			 			<th width="200" class="center"></th>
			 		</tr>
			 	</thead>
			 	<tbody></tbody>
			 	<tfoot></tfoot>
			</table>
		</div>
	</div>
</div>

<div class="modal fade" id="modalInfo" tabindex="-1" role="dialog" aria-labelledby="labelModalFormUnidades" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
		<div class="modal-header padding-0 padding-bottom-10 padding-top-10 center margin-bottom-10" style="background: #EEE;">
			<h4 class="modal-title" id="labelModalInfo"></h4>
		</div>
       	<div class="row">
       		<div class="col-md-6">
	        	<div class="row">
	        		
	        		<div id="" class="profile-user-info profile-user-info-striped">
					<div class="profile-info-row">
						<div class="profile-info-name"> UNIDAD: </div>
						<div class="profile-info-value">
							<span id="txtUnidad"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name"> Propietario </div>
						<div class="profile-info-value">
							<span id="txtPropietario"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name">F. Emisión</div>
						<div class="profile-info-value">
							<span id="txtFechaEmision"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name"> Total Emitido S/.</div>

						<div class="profile-info-value">
							<span id="txtEmision"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name">Total Debe S/.</div>
						<div class="profile-info-value">
							<span id="txtDebe"></span>
						</div>
					</div>
				</div>

	        	</div>
	        </div>
	        <div class="col-md-6">
	        	
	        	<div class="row">
	        		<div id="" class="profile-user-info profile-user-info-striped">
	        		<div class="profile-info-row">
						<div class="profile-info-name">N° documento</div>
						<div class="profile-info-value">
							<span id="txtNroDocumento"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name"> Residente </div>
						<div class="profile-info-value">
							<span id="txtResidente"></span>
						</div>
					</div>
	        		<div class="profile-info-row">
						<div class="profile-info-name"> F. Vencimiento: </div>
						<div class="profile-info-value">
							<span id="txtFechaVence"></span>
						</div>
					</div>
					<div class="profile-info-row">
						<div class="profile-info-name"> Total Pagado S/.</div>

						<div class="profile-info-value">
							<span id="txtPagado"></span>
						</div>
					</div>
				</div>
	        	</div>

	        </div>
	        
       	</div>

       	

       	



<div class="margin-top-20">

  <!-- Nav tabs -->
  <ul id="tab-info" class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#concepto" aria-controls="concepto" role="tab" data-toggle="tab">Detalle de Concepto</a></li>
    <li role="presentation"><a href="#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Lista de Pagos</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="concepto">
    	
			<!--<h4 class="modal-title p-title">Concepto</h4>-->
       		
       		<table id="tblConceptos" class="table table-striped table-hover">
			 	<thead>
			 		<tr>
			 			<th><i class="ace-icon fa fa-list blue"></i> Descripción</th>
			 			<th><i class="ace-icon fa fa-money blue"></i> Total</th>
			 			<th><i class="ace-icon fa fa-comments-o blue"></i> Comentario</th>
			 		</tr>
			 	</thead>
			 	<tbody>
			 	</tbody>
			 	<tfoot>
				</tfoot>
			</table>

    </div>
    <div role="tabpanel" class="tab-pane" id="detalle">

			<!--<h4 class="modal-title p-title">Detalle</h4>-->
       		
       		<table id="tblDetalle" class="table table-striped table-hover">
			 	<thead>
			 		<tr>
			 			<th><i class="ace-icon fa fa-file-text-o blue"></i> Tipo Documento</th>
			 			<th><i class="ace-icon fa fa-money blue"></i> Interes</th>
			 			<th><i class="ace-icon fa fa-money blue"></i> Importe</th>
			 			<th><i class="ace-icon fa fa-home blue"></i> Banco</th>
			 			<th><i class="ace-icon fa fa-slack blue"></i> Operación</th>
			 			<th><i class="ace-icon fa fa-calendar blue"></i> Fecha Pago</th>
			 		</tr>
			 	</thead>
			 	<tbody>
			 	</tbody>
			 	<tfoot>
				</tfoot>
			</table>


    </div>

  </div>

</div>

  	 	 
</div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm btn-close" data-dismiss="modal"><i class="ace-icon fa fa-times bigger-110"></i> Cerrar</button>
      </div>

    </div>
  </div>
</div>

<?php $this->inlineScript()
    ->appendFile($this->basePath('/script/ue/cuotas.js?t='.time()),'text/javascript')
?>
