<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Utility\Edificio'           => __DIR__ . '/src/Application/Utility/Edificio.php',
    'Application\Utility\Auditoria'           => __DIR__ . '/src/Application/Utility/Auditoria.php',
    'Application\Model\EdificioTable'        => __DIR__ . '/src/Application/Model/EdificioTable.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\View\Helper\Theme' => __DIR__ . '/src/Application/View/Helper/Theme.php',
    'Application\View\Helper\Text' => __DIR__ . '/src/Application/View/Helper/Text.php',
);
