<div class="row">

	<div class="col-lg-12">
		<a href="javascript:void();" class="btn btn-sm btn-inverse" style="float: right;margin-top: 10px;margin-left: 5px;">
		<i class="ace-icon fa fa-edit bigger-110"></i>Editar información</a>
		<a href="<?php echo $this->url('mantenimiento', array('controller' => 'edificio', 'action' => 'index')); ?>" class="btn btn-sm btn-danger" style="float: right;margin-top: 10px;">
		<i class="ace-icon fa fa-reply bigger-110"></i>Regresar</a>
		<h4 class="header smaller lighter blue">Equipo</h4>
	</div>

	<div class="col-sm-12">
	
		<div class="form-group">
			<label class="col-sm-2 control-label no-padding-right" for="form-field-1"> Nombre </label>
			<div class="col-sm-10" style="margin-bottom: 5px;">
				<select class="form-control" id="form-field-select-1">
					<option value="" disabled=""></option>
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label no-padding-right" for="form-field-1"> Marca </label>
			<div class="col-sm-5" style="margin-bottom: 5px;">
				<input type="text" id="form-field-1" class="col-xs-10 col-sm-12" readonly value="" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label no-padding-right" for="form-field-1">  Número de serie </label>
			<div class="col-sm-3" style="margin-bottom: 5px;">
				<input type="text" id="form-field-1" class="col-xs-10 col-sm-12" readonly value="" />
			</div>
		</div>

	</div>

	<div class="col-lg-12" style="margin-top: 15px;">
		
	<table id="sample-table-1" class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
		<th>Equipo</th>
		<th>Marca</th>
		<th>Número de serie</th>
		<th>Periodicidad</th>
		</tr>
	</thead>

	<tbody>
	<tr>
	<td>NULL</td>
	<td class="hidden-480">NULL</td>
	<td>NULL</td>

	<td class="hidden-480">
	<span class="label label-sm label-warning">NULL</span>
	</td>

	</tr>
	 
	</tbody>
	</table>

	</div>

</div>